// The notable roster: who exists, what they do, and how their opinion of the
// player moves.
//
// Notables are not generated by the world generator and frozen into the save.
// They are a population that fills seats, does a job, ages out of office, and
// is replaced, because the alternative has two failures. A fixed roster means
// the same three names ask in every town for the whole run, and it means a
// notable the player has burned through is never replaced by somebody who has
// not met them. Both make the requesters stop being people.
//
// A seat is filled from the settlement's own data rather than at random, which
// is the "notables are generated from real local data (industries, population)"
// rule in QUESTS_AND_NOTABLES.md section 2. A port gets a merchant, a town with
// workshops gets a foreman, a place with a crime problem gets a gang boss, and
// a hungry town gets a headman who will ask for grain. The role is what decides
// which issues a person will put their name to, so the mapping from local
// conditions to requests is a rule in one table rather than a coincidence.

package issue

import (
	"mbclone/simulation/internal/model"
	"mbclone/simulation/internal/rng"
	"mbclone/simulation/internal/sim"
	"mbclone/simulation/internal/systems/shared"
)

// roleEligibility says which issues a role will put their name to.
//
// This is the whole of "generation per notable". Without it every person in
// every town would be willing to ask for anything, a gang boss would end up
// hauling sacks of grain, and the request would carry no information about who
// made it. A request identifies itself by its author, so the author's
// occupation has to constrain it.
var roleEligibility = [model.NotableRoleCount]struct {
	deliver   bool
	clearHide bool
	escort    bool
}{
	model.RoleMayor:          {deliver: true, clearHide: true},
	model.RoleForeman:        {deliver: true, escort: true},
	model.RoleMerchant:       {deliver: true, escort: true},
	model.RoleShopkeeper:     {deliver: true},
	model.RoleHeadman:        {deliver: true},
	model.RoleDoctor:         {deliver: true},
	model.RoleGangBoss:       {clearHide: true},
	model.RoleMilitiaCaptain: {clearHide: true},
}

// canOffer reports whether a role will ask for a kind of issue.
func canOffer(role model.NotableRole, kind model.IssueKind) bool {
	if role < 0 || int(role) >= model.NotableRoleCount {
		return false
	}
	e := roleEligibility[role]
	switch kind {
	case model.IssueDeliverGoods:
		return e.deliver
	case model.IssueClearHideout:
		return e.clearHide
	case model.IssueEscort:
		return e.escort
	}
	return false
}

// roleOrder is the order roles are considered in when a seat is filled, chosen
// so the most consequential condition about a settlement is looked at first: a
// place with a crime problem gets a gang boss to answer for it, and a place
// without one does not get a gang boss at all. It is a table rather than a
// chain of comparisons because the conditions overlap, and a town that is both
// hungry and dangerous should get a headman and a gang boss rather than
// whichever comparison happened to be written first.
var roleOrder = []model.NotableRole{
	model.RoleGangBoss,
	model.RoleHeadman,
	model.RoleMilitiaCaptain,
	model.RoleForeman,
	model.RoleMerchant,
	model.RoleDoctor,
	model.RoleMayor,
	model.RoleShopkeeper,
}

// seatContext is what is known about a settlement when a seat is being filled.
// It is gathered once per settlement per tick rather than passed around as a
// pointer to the settlement, because a village notable and a town notable are
// filled by the same rule from different fields, and one struct makes that
// difference explicit rather than a nil check further down.
type seatContext struct {
	townID    int
	villageID int
	// workshops counts the workshops in the settlement, which is what makes
	// it a foreman's town rather than a merchant's.
	workshops int
	// port marks a town with a harbour, where a merchant is the natural seat.
	port bool
	// foodDays is the settlement's days of food, read from the food system's
	// own field rather than recomputed.
	foodDays float64
	// crime is the town's crime level, or zero for a village, which has no
	// field of its own and inherits the trouble of the town it sells to.
	crime float64
	// safety is the road leaving the settlement, or one for a village whose
	// roads are its town's business.
	safety float64
	// power is the settlement's standing, which sets how much a person in it
	// can sway and therefore what their requests are worth.
	power float64
	// population is the settlement's people, which scales the power.
	population float64
	// name is the settlement's name, for the generated person's name.
	name string
}

// justified reports whether a settlement's own condition calls for a person in
// a particular job.
//
// This is the whole of seat filling. A settlement is given a gang boss because it
// has a crime problem and a headman because it is hungry, and when a town's
// conditions stop calling for somebody the seat is not refilled with them. The
// consequence worth stating is the one a reader might expect to go the other way:
// a quiet, well-fed, safe town does not get a gang boss, because a gang boss in
// a town with no gangs is a person with nothing to do and nobody to ask.
//
// A role with no condition of its own is always justified. A town has a mayor
// whether or not anything is wrong, and a doctor because people get ill.
func (c seatContext) justified(role model.NotableRole) bool {
	switch role {
	case model.RoleGangBoss:
		return c.crime >= crimeGangBoss
	case model.RoleMilitiaCaptain:
		// A weaker threshold than the gang boss's, and deliberately overlapping:
		// a town that is becoming unsafe needs a militia before it needs
		// somebody to negotiate with whoever is making it unsafe.
		return c.crime >= crimeMilitia
	case model.RoleHeadman:
		return c.foodDays < foodDaysHeadman
	case model.RoleForeman:
		return c.workshops > 0
	case model.RoleMerchant:
		return c.port || c.safety < safetyMerchant
	case model.RoleDoctor:
		return c.population > populationDoctor
	case model.RoleMayor, model.RoleShopkeeper:
		// Unconditional. A town has a mayor and a shopkeeper whatever its state,
		// and they are the fallback when nothing more specific is called for.
		return true
	}
	return false
}

// Thresholds for seat filling, named so a reader can see the whole ordering in
// one place rather than holding four numbers in their head: half a crime level
// before a gang boss, a third before a militia, twelve days of food before a
// headman, and so on.
//
// They are deliberately the same numbers the request triggers use. A seat exists
// so that the request a condition would otherwise go unmade has somebody to make
// it, so a gang boss seated at 0.5 crime is the person who can ask for the
// hideout cleared at 0.5 crime, and the two cannot drift apart.
const (
	crimeGangBoss    = 0.5
	crimeMilitia     = 0.35
	foodDaysHeadman  = 12.0
	safetyMerchant   = 0.6
	populationDoctor = 1500
)

// powerOf is how much a person in a settlement can sway it, 0-1.
//
// It scales with the settlement's prosperity and population and with the size
// of the seat being filled, so a foreman in a workshop town carries more than a
// shopkeeper in a hamlet. A notable with no power has nothing to offer and
// nothing to lose, which is why this is not a decorative number: it is the
// multiplier on every reward and every penalty the person hands out.
func powerOf(c seatContext, role model.NotableRole) float64 {
	p := 0.2
	if c.power > 0 {
		p += 0.4 * shared.Clamp01(c.power)
	}
	// A person with a specific job is listened to more than a generalist, and
	// a role that answers for a crisis is listened to most of all.
	switch role {
	case model.RoleMayor, model.RoleGangBoss, model.RoleHeadman:
		p += 0.25
	case model.RoleMilitiaCaptain, model.RoleForeman:
		p += 0.15
	}
	if c.population > 3000 {
		p += 0.1
	}
	return shared.Clamp01(p)
}

// roster fills empty seats and retires people whose term is up.
//
// It runs before generation so that a settlement which has just gained a
// workshop, or just lost its last gang, has the right person in place before
// the tick asks anybody for anything. Retiring is separate from deleting: a
// retired notable stays in state so an issue of theirs that resolves this tick
// still resolves to somebody, and only stops being offered.
func roster(v *sim.View, w *sim.WriteSet) {
	cfg := v.Cfg.Issue
	rng := v.Rng.Derive("issue-roster")

	// Retirement first, so a seat vacated this tick is refilled this tick
	// rather than leaving a town one influential man short for a day.
	for _, nid := range v.State.NotableIDs() {
		n := v.State.Notables[nid]
		if n == nil || !n.IsActive {
			continue
		}
		tenure := float64(v.Tick-n.BornTick) + 1
		if tenure < cfg.NotableTenureDays {
			continue
		}
		if !rng.Chance(cfg.NotableRetireChance) {
			continue
		}
		if n.OpenIssues > 0 {
			// A person does not walk out of town with requests outstanding.
			// Retiring them would leave those requests with nobody to be paid
			// or aggrieved against, and the cost of ignoring an issue is
			// precisely that somebody is left holding it.
			continue
		}
		w.Set(model.KindNotable, nid, "notable_active", 0,
			shared.ReadString(
				shared.PairI("tenure_days", int(tenure)),
				shared.PairF("power", n.Power)),
			v.Log.RecentFor(model.KindNotable, nid, []string{"notable_power"}, 2),
			"retired after a long term")
	}

	fillSeats(v, w, rng)
}

// fillSeats puts a person in every empty seat, town by town and then village by
// village.
func fillSeats(v *sim.View, w *sim.WriteSet, rng *rng.Rng) {
	bySettlement := seatsBySettlement(v)
	for _, tid := range v.State.TownIDs() {
		ctx := townSeatContext(v, tid)
		if ctx == nil {
			continue
		}
		seats := int(v.Cfg.Issue.NotablesPerTown)
		fill(v, w, rng, bySettlement, *ctx, seats)
	}
	for _, vid := range v.State.VillageIDs() {
		ctx := villageSeatContext(v, vid)
		if ctx == nil {
			continue
		}
		seats := int(v.Cfg.Issue.NotablesPerVillage)
		fill(v, w, rng, bySettlement, *ctx, seats)
	}
}

// seatsBySettlement counts the notables attached to each settlement, keyed the
// same way the tally keys them, so filling a seat and counting a live issue
// agree on what "a settlement" is.
func seatsBySettlement(v *sim.View) map[int]int {
	out := map[int]int{}
	for _, nid := range v.State.NotableIDs() {
		n := v.State.Notables[nid]
		if n == nil || !n.IsActive {
			continue
		}
		key := -1
		if n.TownID >= 0 {
			key = n.TownID
		} else if n.VillageID >= 0 {
			key = n.VillageID + settlementStride
		}
		if key >= 0 {
			out[key]++
		}
	}
	return out
}

// fill seats a settlement up to its quota, skipping roles already held.
//
// A settlement never gets two people in the same job. A town with two merchants
// would generate two delivery requests a day from the same larder and one
// escort request from two people who are both afraid of the same road, which
// reads as a world with a surplus of problems rather than a town with a
// shortage of grain.
//
// A settlement with nobody in it gets no seats at all. A notable is a person
// with local power, and there is no such thing in a place whose population is
// zero; seating one there would have it file requests about a larder that has
// no mouths to fill, which is how a request ends up with nothing at stake.
func fill(v *sim.View, w *sim.WriteSet, rng *rng.Rng, seats map[int]int, ctx seatContext, quota int) {
	key := settlementKeyOf(ctx.townID, ctx.villageID)
	if key < 0 || ctx.population <= 0 {
		return
	}
	held := heldRoles(v, ctx)
	for seats[key] < quota {
		role, ok := nextRole(ctx, held)
		if !ok {
			// Every role this settlement can justify is already held.
			return
		}
		held[role] = true
		person := newNotable(v, rng, ctx, role)
		// The identifier is allocated inside the create, at commit time,
		// rather than here, so that a create never depends on a number this
		// tick guessed.
		w.CreateEntity(func(s *model.State) {
			person.ID = s.NewID(model.IDNotable)
			s.Notables[person.ID] = person
		})
		seats[key]++
	}
}

// heldRoles returns the roles already filled in a settlement, so a second seat
// is not filled with the same job twice.
func heldRoles(v *sim.View, ctx seatContext) map[model.NotableRole]bool {
	out := map[model.NotableRole]bool{}
	for _, nid := range v.State.NotableIDs() {
		n := v.State.Notables[nid]
		if n == nil || !n.IsActive {
			continue
		}
		if n.TownID != ctx.townID || n.VillageID != ctx.villageID {
			continue
		}
		out[n.Role] = true
	}
	return out
}

// nextRole picks the role for the next seat: the settlement's most pressing
// unheld condition first, and the unconditional seats last.
//
// roleOrder walks from the most consequential condition to the least, so a town
// that is both short of food and short of law gets a headman and a gang boss
// rather than whichever comparison happened to be written first. Only roles the
// settlement's own state justifies are considered, which is why a quiet, fed,
// safe town ends up with a mayor rather than a gang boss: there is nothing here
// for a gang boss to do.
//
// It returns false when every role the settlement could justify is already held,
// which is the honest answer for a hamlet with one seat and a police force.
func nextRole(ctx seatContext, held map[model.NotableRole]bool) (model.NotableRole, bool) {
	for _, role := range roleOrder {
		if held[role] || !ctx.justified(role) {
			continue
		}
		return role, true
	}
	return model.RoleMayor, false
}

// newNotable builds a person for a seat.
//
// The name is composed from the settlement's own name rather than drawn from a
// list, so a person can be traced back to the place that made them and the
// quest log can say which town asked. A power figure comes from the settlement
// rather than from a draw, for the same reason: the notable's standing is a
// fact about their town.
func newNotable(v *sim.View, rng *rng.Rng, ctx seatContext, role model.NotableRole) *model.Notable {
	n := &model.Notable{
		ID:            -1,
		Name:          notableName(ctx, role, rng),
		Role:          role,
		TownID:        ctx.townID,
		VillageID:     ctx.villageID,
		Power:         powerOf(ctx, role),
		Relation:      0,
		OpenIssues:    0,
		Grievance:     0,
		CooldownUntil: 0,
		BornTick:      v.Tick,
		TenureDays:    0,
		LastOfferTick: -1,
		IsActive:      true,
	}
	return n
}

// nameSuffixes are the ways a person is addressed in their settlement. Picking
// one at random per notable is enough: the point is that the name reads as
// somebody's, and that a reader can tell two notables apart, not that it is
// drawn from a deep well.
var nameSuffixes = []string{"of the town", "the elder", "the younger", "Steadfast", "Fairweather", "the Quiet", "Redhand", "Longshanks"}

// notableName composes a name for a seat.
func notableName(ctx seatContext, role model.NotableRole, rng *rng.Rng) string {
	roleName := "citizen"
	if int(role) < len(model.NotableRoleNames) {
		roleName = model.NotableRoleNames[role]
	}
	base := ctx.name
	if base == "" {
		base = "the settlement"
	}
	return roleName + " " + nameSuffixes[rng.Intn(len(nameSuffixes))] + " of " + base
}

// townSeatContext gathers what is known about a town, or nil if it is gone.
func townSeatContext(v *sim.View, tid int) *seatContext {
	t := v.State.Towns[tid]
	if t == nil {
		return nil
	}
	workshops := 0
	for _, wid := range v.State.WorkshopIDs() {
		wk := v.State.Workshops[wid]
		if wk != nil && wk.TownID == tid {
			workshops++
		}
	}
	// The nearest road out of the town, which is the road an escort would be
	// about. Reading the actual route rather than the town's own field is what
	// makes the request about the road that exists.
	safety := 1.0
	best := -1.0
	for _, rid := range v.State.RouteIDs() {
		r := v.State.Routes[rid]
		if r == nil {
			continue
		}
		if r.TownA != tid && r.TownB != tid {
			continue
		}
		d := v.State.DistanceBetweenTowns(tid, otherEnd(r, tid))
		if best < 0 || d < best {
			best = d
			safety = r.Safety
		}
	}
	return &seatContext{
		townID:     tid,
		villageID:  -1,
		workshops:  workshops,
		port:       t.IsPort,
		foodDays:   t.FoodDays,
		crime:      t.Crime,
		safety:     safety,
		power:      t.Prosperity,
		population: t.Population,
		name:       t.Name,
	}
}

// villageSeatContext gathers what is known about a village, or nil if it is
// gone.
//
// A village has no crime of its own and no road of its own: its headman
// inherits the crime of the town they sell to and the road safety of the route
// from it, because that is the road their grain actually travels on. Reading
// the town's crime rather than inventing a village crime is what keeps a
// headman from asking for a hideout to be cleared in a place that has none.
func villageSeatContext(v *sim.View, vid int) *seatContext {
	x := v.State.Villages[vid]
	if x == nil {
		return nil
	}
	crime := 0.0
	safety := 1.0
	if t := v.State.Towns[x.TownID]; t != nil {
		crime = t.Crime
	}
	for _, rid := range v.State.RouteIDs() {
		r := v.State.Routes[rid]
		if r == nil {
			continue
		}
		if r.TownA == x.TownID || r.TownB == x.TownID {
			safety = r.Safety
			break
		}
	}
	return &seatContext{
		townID:     -1,
		villageID:  vid,
		workshops:  0,
		port:       false,
		foodDays:   villageFoodDays(v, x),
		crime:      crime,
		safety:     safety,
		power:      x.Prosperity,
		population: x.Population,
		name:       x.Name,
	}
}

// villageFoodDays converts a village's food into the days its people could
// live on it, which is the same unit the food system's town field is in and so
// the same number a deliver-goods trigger can be written against.
//
// A village's own food is its harvest in person-days, and its people eat the
// same person-days per head per day the town does, so the two are directly
// comparable without this system taking a position on either.
func villageFoodDays(v *sim.View, x *model.Village) float64 {
	perHead := v.Cfg.Food.PersonDaysPerPersonDay
	if perHead <= 0 || x.Population <= 0 {
		return 0
	}
	return x.Food / (x.Population * perHead)
}
