"""The data manifest: every dataset with its source, date, digest, and gaps.

CONSTITUTION.md section 1.1: "Where real data has gaps, use the nearest real
source (nearest census decade, nearest measured value) and log the gap and the
substitution in CHANGELOG.md under Data notes."

agents/README.md Contract A point 3 requires the same thing as a checked-in file.
This module builds that file from ``worlddata.datasets`` plus what actually
happened during the run, so a dataset cannot be consumed without being declared.

Three files are written:

  docs/DATA_MANIFEST.md   the human-readable record, checked in
  dist/MANIFEST.json      the machine-readable form, ships with the data
  docs/DATA_NOTES.md      the gap and substitution log, in the shape CHANGELOG.md
                          expects under Data notes
"""

from __future__ import annotations

import json
import platform
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from . import datasets as dataset_registry
from .config import Config
from .errors import WorldDataError
from .fetch import sha256_of_file


@dataclass
class DatasetRecord:
    """One dataset and the evidence about the exact bytes used."""

    key: str
    source: str
    version: str
    url: str
    filename: str
    licence: str
    used_for: str
    notes: str
    retrieved_at: str
    bytes: int | None
    sha256: str | None
    sha256_published_upstream: bool
    sha256_verification: str
    rows_read: int | None = None
    gap_note: str = ""


@dataclass
class Manifest:
    """Everything the manifest needs, assembled by the pipeline."""

    generated_at: str
    census_year: int
    estimates_vintage: int
    datasets: list[DatasetRecord] = field(default_factory=list)
    gaps: list[dict[str, str]] = field(default_factory=list)
    diagnostics: list[str] = field(default_factory=list)
    environment: dict[str, str] = field(default_factory=dict)

    def as_dict(self) -> dict[str, Any]:
        return {
            "title": "World data manifest",
            "description": (
                "Every external dataset the Phase 0 world data pipeline consumed, with its source, URL, "
                "date retrieved, version, digest, and any gap or substitution. Generated by the run that "
                "produced the data, so it cannot drift from what was actually read."
            ),
            "generated_at": self.generated_at,
            "generated_at_iso": datetime.now(timezone.utc).isoformat(),
            "census_year": self.census_year,
            "population_estimates_vintage": self.estimates_vintage,
            "environment": self.environment,
            "datasets": [
                {
                    "key": record.key,
                    "source": record.source,
                    "version": record.version,
                    "url": record.url,
                    "file": record.filename,
                    "licence": record.licence,
                    "used_for": record.used_for,
                    "bytes": record.bytes,
                    "sha256": record.sha256,
                    "sha256_published_upstream": record.sha256_published_upstream,
                    "sha256_verification": record.sha256_verification,
                    "rows_read": record.rows_read,
                    "retrieved_at": record.retrieved_at,
                    "notes": record.notes,
                    "gap_note": record.gap_note,
                }
                for record in self.datasets
            ],
            "declared_gaps": self.gaps,
            "run_diagnostics": self.diagnostics,
        }


def build_records(
    config: Config,
    retrieved: dict[str, tuple[str, Path, str]],
    row_counts: dict[str, int],
) -> list[DatasetRecord]:
    """Pair each declared dataset with the file actually downloaded.

    ``retrieved`` maps dataset key to (retrieved_at, path, sha256).
    """
    declared = {
        dataset.key: dataset
        for dataset in dataset_registry.all_datasets(
            census_year=config.census_year,
            popest_vintage=config.estimates_vintage,
            elevation_tiles=config.elevation_tiles,
        )
    }
    records: list[DatasetRecord] = []
    missing: list[str] = []
    for key, dataset in declared.items():
        if key not in retrieved:
            missing.append(key)
            continue
        retrieved_at, path, digest = retrieved[key]
        if not path.is_file():
            raise WorldDataError(
                f"dataset {key} was recorded as retrieved but {path} does not exist; the manifest would be "
                "claiming a download that is not there"
            )
        actual = sha256_of_file(path)
        if actual != digest:
            raise WorldDataError(
                f"dataset {key} digest changed between the download and the manifest run "
                f"({digest} then {actual}); the raw file was modified mid-run"
            )
        records.append(
            DatasetRecord(
                key=key,
                source=dataset.source,
                version=dataset.version,
                url=dataset.url,
                filename=dataset.filename,
                licence=dataset.licence,
                used_for=dataset.used_for,
                notes=dataset.notes,
                retrieved_at=retrieved_at,
                bytes=path.stat().st_size,
                sha256=actual,
                sha256_published_upstream=dataset.upstream_digest_available,
                sha256_verification=(
                    "compared against the digest recorded at download time and re-computed now; they match"
                    if dataset.upstream_digest_available
                    else (
                        "No upstream digest is published for this file, so no comparison against the "
                        "publisher is possible. The digest below is the one this pipeline computed; the "
                        "recorded-digest check on later runs catches any change to the local copy. This is "
                        "logged as a gap in the Data notes."
                    )
                ),
                rows_read=row_counts.get(key),
            )
        )
    if missing:
        raise WorldDataError(
            f"these datasets were declared but never downloaded: {missing}. The manifest must describe "
            "everything the run consumed."
        )
    return records


def describe_environment() -> dict[str, str]:
    """Versions of the things that affect reproducibility."""
    import numpy

    environment = {
        "python": sys.version.split()[0],
        "platform": platform.platform(),
        "numpy": numpy.__version__,
    }
    for name in ("pandas", "pyarrow"):
        try:
            module = __import__(name)
            environment[name] = getattr(module, "__version__", "unknown")
        except ImportError:
            environment[name] = "not installed"
    for name in ("geopandas", "shapely", "fiona", "psycopg"):
        try:
            __import__(name)
            environment[name] = "installed"
        except ImportError:
            environment[name] = "not installed"
    return environment


def write_manifests(config: Config, manifest: Manifest) -> dict[str, Path]:
    """Write the manifest as JSON, Markdown and a CHANGELOG-shaped gap log."""
    payload = manifest.as_dict()
    export_dir = config.path_for("export_dir")
    report_dir = config.path_for("report_dir")
    export_dir.mkdir(parents=True, exist_ok=True)
    report_dir.mkdir(parents=True, exist_ok=True)

    json_path = export_dir / "MANIFEST.json"
    json_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    markdown_path = report_dir / "DATA_MANIFEST.md"
    markdown_path.write_text(_render_markdown(payload), encoding="utf-8")

    notes_path = report_dir / "DATA_NOTES.md"
    notes_path.write_text(_render_data_notes(payload), encoding="utf-8")

    return {"json": json_path, "markdown": markdown_path, "data_notes": notes_path}


def _render_markdown(payload: dict[str, Any]) -> str:
    lines = [
        "# Data manifest",
        "",
        "Generated by `services/world-data`. Every dataset the pipeline consumed, with the source it came",
        "from, when it was retrieved, what version it is, the digest of the exact bytes used, and every",
        "gap. Regenerated by `python -m worlddata run`; do not hand-edit.",
        "",
        f"- Generated: `{payload['generated_at']}`",
        f"- Population vintage: Census {payload['census_year']}, "
        f"estimates vintage {payload['population_estimates_vintage']}",
        f"- Environment: " + ", ".join(f"`{key}` {value}" for key, value in payload["environment"].items()),
        "",
        "## Datasets",
        "",
        "| Dataset | Source | Version | URL | Retrieved | Bytes | SHA-256 | Rows read |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for record in payload["datasets"]:
        lines.append(
            f"| `{record['key']}` | {record['source']} | {record['version']} | <{record['url']}> | "
            f"{record['retrieved_at']} | {record['bytes']:,} | `{str(record['sha256'])[:16]}...` | "
            f"{record['rows_read'] if record['rows_read'] is not None else 'n/a'} |"
        )

    lines += ["", "## Licence and use", "", "| Dataset | Licence | Used for |", "|---|---|---|"]
    for record in payload["datasets"]:
        lines.append(f"| `{record['key']}` | {record['licence']} | {record['used_for']} |")

    lines += ["", "## Digest verification", ""]
    for record in payload["datasets"]:
        lines.append(f"- `{record['key']}`: {record['sha256_verification']}")

    lines += ["", "## Declared gaps and substitutions", ""]
    for gap in payload["declared_gaps"]:
        lines += [
            f"### {gap['gap']}",
            "",
            f"- **Wanted for:** {gap['wanted_for']}",
            f"- **Why it is missing:** {gap['why_missing']}",
            f"- **Substitution used:** {gap['substitution']}",
            f"- **What this means for the output:** {gap['honesty']}",
            "",
        ]

    lines += ["## Run diagnostics", ""]
    for note in payload["run_diagnostics"]:
        lines.append(f"- {note}")
    lines.append("")
    return "\n".join(lines)


def _render_data_notes(payload: dict[str, Any]) -> str:
    """The gap log, in the column shape CHANGELOG.md uses under Data notes."""
    lines = [
        "# Data notes",
        "",
        "Gap and substitution log in the column shape `CHANGELOG.md` expects under **Data notes**",
        "(CONSTITUTION.md section 1.1). Agent 1 does not edit `CHANGELOG.md`; these rows are the",
        "material to paste there. Regenerated by the pipeline.",
        "",
        "| Date | Dataset | Source | Version or date | Gaps | Handling |",
        "|---|---|---|---|---|---|",
    ]
    today = payload["generated_at"][:10]
    for record in payload["datasets"]:
        gap = record["gap_note"] or record["sha256_verification"]
        lines.append(
            f"| {today} | {record['key']} | {record['source']} | {record['version']} | "
            f"{gap} | {record['used_for']} |"
        )
    lines.append("")
    for gap in payload["declared_gaps"]:
        lines.append(f"- **{gap['gap']}** - {gap['honesty']}")
    lines.append("")
    return "\n".join(lines)
