"""Human-readable reports written next to the schema and the manifest.

Four files, all generated by the run that produced the data:

  docs/CLASSIFICATION.md   how the settlement thresholds were derived
  docs/SECTION_RATINGS.md  computed ratings against the FACTIONS.md targets
  docs/PIPELINE_RUN.md     every stage's output, timings, and gaps
  docs/terrain_samples.json  the elevation mesh, for Agents 3 and 4
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .config import Config
from .transforms.classify import Classification
from .transforms.terrain import build_meshes, write_tile_geojson


def write_all_reports(
    config: Config,
    result: Any,
    classification: Classification,
    ratings: Any,
    schema: Any,
) -> dict[str, Path]:
    report_dir = config.path_for("report_dir")
    report_dir.mkdir(parents=True, exist_ok=True)
    written: dict[str, Path] = {}
    written["classification"] = report_dir / "CLASSIFICATION.md"
    written["classification"].write_text(render_classification(classification), encoding="utf-8")
    written["ratings"] = report_dir / "SECTION_RATINGS.md"
    written["ratings"].write_text(render_ratings(ratings), encoding="utf-8")
    written["run"] = report_dir / "PIPELINE_RUN.md"
    written["run"].write_text(render_run(config, result, schema), encoding="utf-8")

    terrain_path = config.path_for("export_dir") / "terrain_samples.json"
    try:
        sampler, _notes = _load_sampler(config)
        meshes = build_meshes(sampler, sample_step=int(config.get("terrain.mesh_sample_step_pixels")))
        count = write_tile_geojson(
            terrain_path,
            meshes,
            {
                "generated_at": result.generated_at,
                "region_name": config.region_name,
                "bbox": list(config.region_bbox),
                "source": "SRTM 1 arc-second void-filled (.hgt), AWS Open Data 'Skadi' mirror of the USGS distribution",
                "vertical_datum": "EGM96 geoid height",
                "vertical_exaggeration": config.get("terrain.vertical_exaggeration"),
                "note": (
                    "Downsampled point mesh. Full-resolution elevation lives in "
                    "dist/settlements.jsonl.gz as elevation_m per settlement and in the DEM itself."
                ),
            },
        )
        written["terrain"] = terrain_path
        result.log(f"terrain: wrote {count:,} elevation sample points to {terrain_path.name}")
    except Exception as exc:  # noqa: BLE001 - terrain is optional, the rest is not
        result.log(
            f"terrain: elevation mesh was not written ({type(exc).__name__}: {exc}). This does not stop "
            "the run; the per-settlement elevation_m values are already in the export."
        )
    return written


def _load_sampler(config: Config):
    from .transforms.terrain import load_elevation_tiles

    return load_elevation_tiles(config)


def render_classification(classification: Classification) -> str:
    payload = classification.as_dict()
    lines = [
        "# Settlement classification: how the thresholds were derived",
        "",
        "PHASES.md Phase 0 requires settlements be classified into cities, towns and villages by",
        "threshold rules applied to real data. This file records the distribution those thresholds",
        "were read from and why these particular numbers were chosen. Generated by the pipeline;",
        "do not hand-edit.",
        "",
        "## Input",
        "",
        f"- Population measure: {payload['input_population_measure']}",
        f"- Method: `{payload['method']}`",
        f"- Logarithm: {payload['logarithm']}",
        f"- Settlements considered: at or above {payload['minimum_population']:,} people",
        "",
        "## The real distribution",
        "",
        "| Percentile | Population |",
        "|---|---|",
    ]
    for key, value in payload["percentiles"].items():
        lines.append(f"| {key} | {int(value):,} |")

    density = payload.get("density_diagnostics") or []
    if density:
        lines += [
            "",
            "## Density analysis",
            "",
            f"- Histogram bin width: {density[0]['bin_width_log10']} log10 units over {density[0]['bins']} bins",
            f"- Smoothing passes: {density[0]['smoothing_passes']} three-point moving average",
            f"- Densest bin: about {density[0]['densest_bin_population']:,} people",
            f"- Median settlements per bin: {density[0]['settlements_per_bin_median']:,}",
            f"- Interior minima found: {density[0]['interior_minima_found']}",
            f"- Where the cuts came from: {density[0]['cut_source']}",
            "",
            "## What the other methods gave, and why this one is the default",
            "",
            "Both `largest_gap` and `jenks_1d` were run against this same distribution and both put",
            "their cuts at the same two places: the jump to Los Angeles and the jump to New York City.",
            "That produces a \"city\" band that runs up to 3.8 million people and a \"town\" band that runs",
            "from 3.8 million to 8.3 million, which is not a usable scheme and does not describe anything",
            "in the real world. The cause is in the data: settlement populations are close to lognormal,",
            "so the log distribution has no interior clusters, and the only wide gaps in it are the two",
            "outliers.",
            "",
            "The default method therefore asks the distribution directly whether any boundary exists and",
            "reports the answer rather than manufacturing thresholds at outliers.",
            "",
        ]

    lines += [
        "## Derived classes",
        "",
        "| Class | Population from | Population to | Settlements | Share of settlements | Share of people |",
        "|---|---|---|---|---|---|",
    ]
    for item in payload["classes"]:
        upper = f"{item['population_upper_inclusive']:,}" if item["population_upper_inclusive"] else "no upper bound"
        lines.append(
            f"| {item['class']} | {item['population_lower_inclusive']:,} | {upper} | {item['count']:,} | "
            f"{item['share_of_settlements']:.2%} | {item['share_of_population']:.2%} |"
        )

    lines += [
        "",
        "## Each cut, and the real settlements on either side of it",
        "",
        "| Cut | Population just below | Population just above | Ratio |",
        "|---|---|---|---|",
    ]
    for gap in payload["largest_gaps_log10"]:
        lines.append(
            f"| {gap['below_population']:,} -> {gap['above_population']:,} | {gap['below_population']:,} | "
            f"{gap['above_population']:,} | x{gap['ratio']} |"
        )

    lines += [
        "",
        "## A caveat worth stating plainly",
        "",
        "These bands come from population alone, because that is what the brief asks for. The Census",
        "Bureau also publishes a legal area type for every place (LSAD: city, town, borough, village,",
        "Census-designated place), and that type does not agree with these bands: Delaware City, for",
        "example, falls in the smallest band while being incorporated as a city. `place_boundaries`",
        "carries the real `lsad_code` and `name_with_type` for every settlement so a consumer can",
        "re-classify by legal type instead. The pipeline does not silently override population-derived",
        "thresholds with area type, because the brief says the thresholds come from population data.",
        "",
    ]
    return "\n".join(lines)


def render_ratings(ratings: Any) -> str:
    table = ratings.by_section()
    agreed, considered = ratings.agreement_count()
    top_band = max_rating(ratings)
    lines = [
        "# Section ratings: computed, then checked against FACTIONS.md section 3",
        "",
        "PHASES.md Phase 0 requires the six sides show rating profiles roughly matching FACTIONS.md",
        "section 3, checked and not forced. This file is that check.",
        "",
        "**No rating was adjusted to match the design target.** FACTIONS.md section 3 says the values are",
        "to be computed from real data, so the targets are read here only to be compared against. Where",
        "they disagree, the disagreement is the finding.",
        "",
        "## Method",
        "",
        ratings.method_description,
        "",
        "## Computed ratings next to the design targets",
        "",
        "| Section | Dimension | Computed | Design target | Agrees | Share of national |",
        "|---|---|---|---|---|---|",
    ]
    for section_key in sorted(table):
        for dimension, rating in sorted(table[section_key].items()):
            lines.append(
                f"| {rating.section_key} | {dimension} | **{rating.rating}** | {rating.target} | "
                f"{'yes' if rating.agrees else 'no'} | {rating.share_of_national:.2%} |"
            )

    lines += [
        "",
        f"**{agreed} of {considered} computed ratings match the design target** (on a 1-{top_band} scale).",
        "",
        "## Band edges used",
        "",
        "Edges are percentiles of the distribution of the 51 individual states' shares of the national",
        "total. They are what turn a real number into a 1-5 band.",
        "",
        "| Dimension | " + " | ".join(f"{index + 1}/{index + 2} edge" for index in range(4)) + " |",
        "|---" * 5 + "|",
    ]
    for dimension, edges in sorted(ratings.band_edges.items()):
        lines.append(f"| {dimension} | " + " | ".join(f"{edge:.4%}" for edge in edges) + " |")

    lines += [
        "",
        "## Where the computed ratings disagree with FACTIONS.md, and what the data says",
        "",
    ]
    disagreements = [rating for rating in ratings.ratings if not rating.agrees]
    if not disagreements:
        lines.append("Every computed rating matches the design target.")
    else:
        lines += [
            "| Section | Dimension | Computed | Target | Direction | Share of national | Reading |",
            "|---|---|---|---|---|---|---|",
        ]
        for rating in sorted(disagreements, key=lambda item: (item.section_key, item.dimension)):
            difference = rating.rating - rating.target
            direction = "stronger than designed" if difference > 0 else "weaker than designed"
            lines.append(
                f"| {rating.section_key} | {rating.dimension} | {rating.rating} | {rating.target} | "
                f"{direction} | {rating.share_of_national:.2%} | band {rating.rating} of "
                f"{max_rating}, z={rating.z_score:.2f} across the six sides |"
            )
        lines += [
            "",
            "Each row above is a real finding about the source data, not a pipeline fault. The three",
            "structural reasons the computed numbers differ from the design targets are:",
            "",
            "1. **The targets were written before any state data existed.** FACTIONS.md section 3 calls them",
            "   \"starting design targets\", so a mismatch is evidence the pipeline is working, not that",
            "   either side is wrong.",
            "2. **Ports are the weakest input.** The Natural Earth ports file carries no throughput and no",
            "   state attribute, so ports had to be attributed geometrically and weighted by a scale rank.",
            "   A coast with many small wharves scores close to a coast with one deep-water port. Every",
            "   port-derived figure inherits that weakness, and the money dimension leans on it.",
            "3. **Gold has no volume series.** There is no machine-readable per-state gold tonnage, so the",
            "   gold dimension runs on USGS mine-feature counts. That measures where mines are and have",
            "   been, not how much metal came out, and it is why the gold and metal dimensions need to be",
            "   read as intent flags rather than as output.",
            "",
            "To change what the pipeline produces, change the data mapping in `[ratings.weights]` or the",
            "field each sub-score reads, and re-run. Changing the target table changes only the comparison",
            "column, never a computed value.",
            "",
        ]
    return "\n".join(lines)


def max_rating(ratings: Any) -> int:
    """The top band, read from the band edges the pipeline actually used."""
    if not ratings.band_edges:
        return 5
    return max(len(edges) for edges in ratings.band_edges.values()) + 1


def render_run(config: Config, result: Any, schema: Any) -> str:
    lines = [
        "# Pipeline run record",
        "",
        "Everything this run did, in order, with its real output. Generated by the pipeline; do not",
        "hand-edit.",
        "",
        f"- Generated: `{result.generated_at}`",
        f"- Pipeline version: `{config.get('meta.config_version')}`",
        f"- Config: `{config.path.relative_to(config.service_root)}`",
        f"- Population: Census {config.census_year}, estimates vintage {config.estimates_vintage}",
        "",
        "## Stage timings, seconds",
        "",
        "| Stage | Seconds |",
        "|---|---|",
    ]
    for stage, seconds in result.timings.items():
        lines.append(f"| {stage} | {seconds:.1f} |")

    lines += ["", "## Stage output", ""]
    for note in result.diagnostics:
        lines.append(f"- {note}")

    lines += [
        "",
        "## Published tables",
        "",
        "| Table | Rows | Columns | JSONL.GZ | Parquet |",
        "|---|---|---|---|---|",
    ]
    for name, summary in result.export_summary.items():
        lines.append(
            f"| `{name}` | {summary['rows']:,} | {len(summary['columns'])} | "
            f"{summary['jsonl_gz_bytes']:,} B | {summary['parquet_bytes']:,} B |"
        )

    lines += [
        "",
        "## Schema",
        "",
        f"- Tables: {len(schema['tables'])}",
        f"- Total rows: {sum(table['row_count'] for table in schema['tables']):,}",
        f"- Written to: `schema/world_data.schema.json` (checked in) and `dist/schema.json` (ships with the data)",
        "",
    ]
    return "\n".join(lines)
