/**
 * State lore (del order 2026-10-04).
 *
 * Deep lore for the major states of the continent: what each state is like
 * after the Unraveling, its key cities, the peoples and ethnic communities
 * that call it home, and its place in the trade network.
 */

import type { CodexEntry } from "./types.js";

export const STATE_ENTRIES: CodexEntry[] = [
  {
    id: "lore-state-new-york",
    title: "New York — The Empire Remnant",
    category: "world",
    tags: ["new-york", "state", "empire"],
    summary: "The old empire's capital region: dense, vertical, and still the continent's financial brain.",
    body: [
      "New York was the capital of the old world in every way that mattered — money, media, culture, power. The Unraveling broke the federal government, but it couldn't break New York's gravity. The money stayed. The people stayed. The towers stayed. What changed is who gives the orders and what the orders are for.",
      "The state divides into two worlds. Downstate is the city and its orbit — the five boroughs, Long Island, the Hudson Valley — packed with every ethnicity on the continent, stacked vertically in towers that the survivors learned to farm, fortify, and wire for power. Upstate is farmland, rust-belt mill towns, and the Adirondack wilds, where the Haudenosaunee communities and the old farming families run things on older terms.",
      "The peoples of New York are the peoples of everywhere: Irish and Italian blocks that survived three centuries of change, Dominican and Puerto Rican neighborhoods that anchor the culture, Chinese and Korean enclaves running the trade houses, Hasidic towns upstate running their own parallel economy, West African merchant networks moving goods through the ports. No other state packs this many communities into this little space, and no other state's politics are this complicated.",
      "In the trade network, New York is the eastern terminus — the end of the Transcontinental Express, the top of the I-95 corridor. Goods flow in from the whole continent and get priced, financed, and re-shipped. The Atlantic Corridor faction holds the ports and the financial district. If you want to move serious money or serious cargo on the east coast, you do it through New York or you don't do it at all.",
    ],
    related: ["lore-city-new-york", "lore-faction-atlantic-corridor"],
  },
  {
    id: "lore-state-california",
    title: "California — The Pacific Compact",
    category: "world",
    tags: ["california", "state", "pacific"],
    summary: "Tech wealth, farm wealth, and desert weirdness — the continent's richest and strangest state.",
    body: [
      "California was the richest state of the old union and it still is, by most measures. The Pacific Compact holds the coast — the Bay Area's tech enclaves, LA's sprawl, San Diego's port — and the Central Valley feeds half the west. The money didn't vanish in the Unraveling; it changed hands, consolidated, and got more serious about security.",
      "The state's peoples are a layered map of migrations. Mexican and Central American communities are the backbone of the farm labor and the port crews, and the old Californio families still hold land grants in the south. The Bay Area's tech enclaves are a mix of every ambitious ethnicity — Indian and Chinese engineers, Eastern European founders, American strivers of every background. The desert interior runs to weirder stock: survivalists, artists, exiles, and the new nomad clans that never stopped moving.",
      "Northern and southern California are different countries that share a flag. The north is tech money, university towns, redwood forests, and a culture of earnest reinvention. The south is ports, studios, sprawl, and a culture of beautiful surfaces over deep machinery. They need each other — the north has the tech, the south has the ports — and they resent each other with the practiced ease of old siblings.",
      "For traders, California is the western terminus: the start of the Transcontinental Express, the top and bottom of the I-5 corridor. High-value manufactured goods flow east; food, fuel, and raw materials flow west. The Pacific Run circuit serves the coast. A caravan that can run California's highways reliably is set for life — if the Compact's tolls don't eat the margin first.",
    ],
    related: ["lore-city-los-angeles", "lore-faction-pacific-compact"],
  },
  {
    id: "lore-state-texas",
    title: "Texas — The Lone Star Frontier",
    category: "world",
    tags: ["texas", "state", "frontier"],
    summary: "Big, proud, and half-independent — the continent's energy heart and its most stubborn polity.",
    body: [
      "Texas never fully accepted the old union and it barely accepts the new order. The Lone Star Frontier holds the state as a near-independent power — its own grid, its own fuel, its own foreign policy. The Unraveling just made official what Texans always believed: Texas is Texas first and everything else second.",
      "The state's economy runs on energy and attitude. The oil fields of the Permian still pump. The refineries of the Gulf Coast still refine. Houston's port moves more tonnage than anywhere else on the continent. And the tech corridor between Austin and Dallas — the 'silicon prairie' — builds the machines that run the new economy. Texas doesn't need anyone, and it makes sure everyone knows it.",
      "The peoples of Texas are a frontier mix. Mexican-Tejano communities predate the state itself and anchor the south. German and Czech farming towns dot the hill country, still speaking the old dialects at church. Black communities in Houston and Dallas built the culture the whole state dances to. The new arrivals — climate refugees from the coasts, tech workers from California, nomads from everywhere — keep the cities churning. And the ranching families, Anglo and Tejano both, still measure a person by their word and their horse.",
      "In the trade network, Texas is the southern hub: Houston anchors the I-10 corridor and the Gulf Express, Dallas sits on I-35 and the Southern Corridor circuit. Fuel flows out; everything else flows in. The Frontier charges what it wants for energy and dares anyone to complain. Caravans running Texas roads carry guards — the frontier is rich, which means it's worth robbing.",
    ],
    related: ["lore-city-houston", "lore-faction-lone-star-frontier"],
  },
  {
    id: "lore-state-florida",
    title: "Florida — The Southern Compact",
    category: "world",
    tags: ["florida", "state", "gulf"],
    summary: "Ports, swamps, and retirees with guns — the gateway to the Gulf and the Caribbean.",
    body: [
      "Florida is where the continent ends and the water begins. The Southern Compact holds the peninsula — Miami's towers, the port complexes, the causeway cities — and projects power across the Gulf and into the Caribbean. Before the Unraveling it was condos and theme parks. Now it's the continent's southern gate, and the gate is armed.",
      "The peoples of Florida are a Caribbean crossroads. Cuban communities in Miami run the trade houses that link the continent to the islands — three generations of exile politics turned into commercial empire. Haitian communities anchor the service economy and the port crews. Puerto Rican and Dominican neighborhoods keep the culture loud. The old Florida crackers — the cattle families of the interior — still run the ranches between the coasts, and the retirees, God help them, are still here, still voting, and now heavily armed.",
      "South Florida and north Florida are different states in all but name. The south is Latin, urban, coastal, and commercial — Miami's logic. The north is southern, rural, and traditional — Jacksonville and the panhandle run on older codes. The Compact holds them together with port revenue and a shared interest in keeping the Gulf open, but the tension never fully goes away.",
      "For traders, Florida is the southeastern terminus: Miami anchors the I-95 corridor's southern end and the Gulf Express. Caribbean goods — sugar, rum, medicine, things that don't get asked about — flow through Miami's port. The Southern Corridor circuit ends here. A caravan that runs the Miami road deals with humidity, hurricanes, and the most competitive merchant houses on the continent.",
    ],
    related: ["lore-city-miami", "lore-faction-southern-compact"],
  },
  {
    id: "lore-state-colorado",
    title: "Colorado — The Mountain Crossroads",
    category: "world",
    tags: ["colorado", "state", "mountains", "front-range"],
    summary: "The continent's spine: where every east-west road crosses the mountains, and the game is played.",
    body: [
      "Colorado is the state the game is played in. The Front Range — Denver, Boulder, Golden, and the satellite towns — is the detailed map, the starting ground, the place where caravans are founded and fortunes are made. The state's geography is the continent's geography in miniature: plains to the east, mountains to the west, and every road between them running through Denver.",
      "The Mountain Alliance holds the high country — the ski towns turned fortresses, the mining districts, the passes. The Front Range cities are the contested lowlands: Halloway holds Denver and the eastern suburbs, Vashti holds Boulder and the foothill towns, and the balance between them is the region's politics. The western slope — Grand Junction, the canyon country — is wilder, poorer, and less governed.",
      "The peoples of Colorado are a mountain mix. The old ranching families — Anglo, Hispanic, and Ute — worked this land before it was a state. The tech transplants of the 2010s and 2020s became the merchant class of the 2030s. The ski-town crews became the mountain infantry. The highlander clans of the foothills — the Vashti and their kin — trace their line to Scottish and Irish miners who never left. And the nomad bands that drift the high passes answer to no one.",
      "In the trade network, Colorado is the hub: Denver sits at the origin of the national map, where I-70, I-80, and I-35 all connect. The Mile-High Loop, the Foothills Run, and the North Corridor serve the local towns; the Transcontinental Express and the Heartland Loop connect the state to the continent. Every long-haul route touches Colorado. That's not an accident of geography — it's the reason the game starts here.",
    ],
    related: ["lore-city-denver", "lore-city-boulder", "lore-city-golden", "lore-faction-mountain-alliance"],
  },
  {
    id: "lore-state-illinois",
    title: "Illinois — The Great Lakes Union",
    category: "world",
    tags: ["illinois", "state", "midwest", "chicago"],
    summary: "Chicago's state: rail yards, grain elevators, and the continent's central market.",
    body: [
      "Illinois is Chicago and the farmland that feeds it. The Great Lakes Union holds the city and the northern counties — the rail yards, the port, the commodity exchanges that price the continent's grain. Downstate is a different world: small towns, big farms, and a culture that regards Chicago the way a body regards a head — necessary, distant, and slightly alien.",
      "Chicago's peoples are the classic American mix, hardened by winters and sharpened by commerce. Polish and Irish neighborhoods built the city's bones. Black communities built its soul — the music, the churches, the political machine. Mexican communities anchor the southwest side and the packing houses. The new arrivals — South Asian tech workers, West African traders, Eastern European contractors — keep the city's churn going. Out in the farm counties, the German and Scandinavian farming families still work the same land their great-grandparents broke.",
      "The city's politics are the state's politics: the machine runs Chicago, Chicago runs Illinois, and downstate grumbles but cashes the checks. The Union's leadership is drawn from the old ward organizations, updated for the new economy — less patronage, more logistics, same ruthlessness. A trader who wants to move grain in volume makes friends in the exchange halls or doesn't move grain.",
      "In the trade network, Chicago is the midwestern hub: the Transcontinental Express passes through, the Heartland Loop starts here, and I-80 and I-55 connect the city to both coasts. Grain flows out in bulk; manufactured goods flow in. The city's markets set the price of food for half the continent. A caravan running the Chicago road carries volume — the margins are thin, but the loads are enormous.",
    ],
    related: ["lore-faction-great-lakes-union"],
  },
  {
    id: "lore-state-washington",
    title: "Washington — The Evergreen Corridor",
    category: "world",
    tags: ["washington", "state", "pacific-northwest"],
    summary: "Rain, tech, and timber — the Pacific Northwest's green fortress.",
    body: [
      "Washington is the green corner of the map: rainforest to the west, desert to the east, and the tech-and-trade corridor of Seattle-Tacoma holding it together. The state's politics run progressive, its economy runs on software and shipping, and its culture runs on a quiet conviction that the Northwest does things better than everywhere else.",
      "Seattle's peoples are a Pacific mix. The old Scandinavian fishing families still work the Sound. Asian communities — Chinese, Vietnamese, Filipino — anchor the International District and the tech workforce. East African immigrants built new communities in the south end. The tribal nations — the Coast Salish peoples — never left and never stopped governing their lands. And the tech transplants, drawn by the big campuses, brought every ethnicity and a shared belief in optimization.",
      "East of the Cascades is a different state: wheat country, apple orchards, the Hanford flats, and a ranching culture that votes red and regards Seattle as a foreign capital. The mountains divide more than weather. The state's unity is a negotiated thing — the west has the money and the ports, the east has the food and the space, and both sides know the deal.",
      "For traders, Washington is the northwestern terminus: Seattle anchors the I-5 corridor's northern end and the Pacific Run circuit. Timber, software, and Pacific Rim goods flow south; food and fuel flow north. The port of Seattle-Tacoma is the continent's Pacific gate. A caravan running the I-5 deals with rain, mountain passes, and the most self-satisfied merchants on the west coast.",
    ],
    related: ["lore-faction-pacific-compact"],
  },
  {
    id: "lore-state-georgia",
    title: "Georgia — The New South",
    category: "world",
    tags: ["georgia", "state", "south", "atlanta"],
    summary: "Atlanta's state: the capital of the New South and the crossroads of the Southeast.",
    body: [
      "Georgia is the New South made concrete: Atlanta's towers rising from the red clay, the world's busiest airport turned caravan hub, and a Black-led political and business class that runs the state's show. The old Georgia of plantations and pecans still exists in the south — the farm counties, the small towns — but the state's gravity is Atlanta, and Atlanta's gravity is Black excellence.",
      "The peoples of Georgia tell the southern story. Black Georgians — descendants of the enslaved, builders of the churches, the colleges, the businesses — are the state's political and cultural core. White Georgians split between the old rural families and the suburban newcomers. The new immigrants — Korean communities in Duluth, Mexican communities in Gainesville's poultry towns, South Asian tech workers in Alpharetta — keep the state's economy churning. The Gullah communities of the coast keep the oldest African traditions on the continent.",
      "Atlanta's logic is connection: the airport, the highways, the rail lines all converge here. The city sells itself as the place where the South does business with the world, and it delivers. The state government follows the city's lead on economics and fights it on culture — the eternal Georgia dance. A trader who understands Atlanta understands the Southeast, because every road in the region leads here.",
      "In the trade network, Georgia is the southeastern hub: Atlanta anchors the I-95 corridor's middle and the Eastern Seaboard circuit. Goods flow north to the Atlantic cities and south to Florida and the Gulf. The city's markets set the price of southern manufactures. A caravan running the Atlanta road deals with the continent's most polished merchant houses — and its most competitive.",
    ],
    related: ["lore-faction-southern-compact"],
  },
  {
    id: "lore-state-arizona",
    title: "Arizona — The Desert Between",
    category: "world",
    tags: ["arizona", "state", "desert", "southwest"],
    summary: "Sun, sand, and sprawl — the desert corridor between California and Texas.",
    body: [
      "Arizona is the desert the continent drives through. Phoenix sprawls across the Salt River valley — five million people in a place that gets eight inches of rain a year, kept alive by canals, aqueducts, and stubbornness. Tucson holds the south. The reservations — Navajo, Hopi, Tohono O'odham — hold the north and east on their own terms. Everything else is highway, desert, and sky.",
      "The peoples of Arizona are a desert mix. Mexican and Tohono O'odham communities predate the border and ignore it. The Mormon farming towns of the north run their own tight, prosperous enclaves. The retirees — the famous Arizona retirees — came for the sun and stayed for the low taxes, and they're organized, armed, and politically formidable. The tribal nations are sovereign powers, not minorities: the Navajo Nation is the largest reservation in the country and governs like it.",
      "Phoenix's existence is a daily argument with the desert, and the desert is winning slowly. Water is the state's politics, its economy, and its existential dread. The canal systems are fortified infrastructure now, guarded like borders. A trader in Arizona thinks about water the way a trader elsewhere thinks about fuel — it's the constraint that shapes every decision.",
      "For traders, Arizona is the southwestern corridor: Phoenix anchors the I-10's middle and the Southern Corridor circuit. Goods flow west to California and east to Texas. The desert crossings are the dangerous part — long, hot, empty stretches where bandits work and breakdowns kill. A caravan running the Arizona road carries extra water, extra guards, and a healthy respect for the sun.",
    ],
    related: ["lore-faction-lone-star-frontier"],
  },
  {
    id: "lore-state-pennsylvania",
    title: "Pennsylvania — The Keystone",
    category: "world",
    tags: ["pennsylvania", "state", "rust-belt", "northeast"],
    summary: "Steel, coal, and stubbornness — the old industrial heart that refuses to die.",
    body: [
      "Pennsylvania is the Keystone State in fact as well as nickname: it holds the Northeast together. Philadelphia anchors the east — the old capital, the port, the medical and university complex. Pittsburgh anchors the west — the steel city, rebuilt around tech and medicine but never forgetting the mills. Between them: the coal counties, the farm counties, the small cities that made things and still do.",
      "The peoples of Pennsylvania are the old American working class in all its variety. Irish and Italian neighborhoods in Philly and Pittsburgh, Polish and Slovak mill towns in the west, German farming communities in the center — the Pennsylvania Dutch still farm Lancaster County with horses. Black communities in both big cities built the churches and the unions. The new immigrants — Dominican in Reading, Mexican in Kennett Square's mushroom farms, South Asian in the Philly suburbs — work the jobs the old stock left.",
      "The state's politics are a permanent negotiation between the two big cities and the 'T' — the vast rural middle that regards both with suspicion. Philadelphia looks east to New York and Washington. Pittsburgh looks west to Ohio and the Midwest. The middle looks inward and votes its resentments. A trader who can navigate all three Pennsylvanias can navigate anywhere.",
      "In the trade network, Pennsylvania is the northeastern corridor: Philadelphia anchors the I-95's middle, Pittsburgh sits on the I-80's eastern end. Steel, coal, and manufactured goods flow east and west. The state's workshops supply half the Northeast. A caravan running the Pennsylvania turnpike deals with hills, weather, and the continent's most experienced industrial merchants.",
    ],
    related: ["lore-faction-atlantic-corridor"],
  },
  {
    id: "lore-state-ohio",
    title: "Ohio — The Crossroads",
    category: "world",
    tags: ["ohio", "state", "midwest", "crossroads"],
    summary: "The state where every road crosses: farms, factories, and the continent's bellwether soul.",
    body: [
      "Ohio is the crossroads of America — the state where north meets south and east meets west, where every highway crosses and every election is decided. Columbus holds the center, Cleveland the north, Cincinnati the south, and the spaces between are farm counties and factory towns in every stage of boom and rust.",
      "The peoples of Ohio are the Midwest in miniature. German farming families work the western counties. Irish and Italian neighborhoods anchor the old industrial cities. Black communities in Cleveland, Columbus, and Cincinnati built the churches, the music, and the political organizations. The Appalachian counties of the southeast — the Ohio River towns — run on hillfolk codes older than the state. The new immigrants — Somali in Columbus, Mexican in the farm towns, South Asian in the suburbs — keep the state's churn going.",
      "Ohio's cities each face a different direction. Cleveland looks north to the Lakes and the old industrial economy. Cincinnati looks south to Kentucky and the river trade. Columbus looks inward — the capital, the university, the insurance and tech offices — and grows while the others argue about the past. A trader in Ohio learns to read each city's orientation or gets the direction wrong.",
      "For traders, Ohio is the central interchange: I-70, I-80, and I-75 all cross here. Goods moving between the Northeast, the Midwest, and the South pass through Ohio's highways. The state's markets are the continent's price-discovery mechanism for grain, steel, and manufactured goods. A caravan running the Ohio roads is never far from a market, a meal, or a competitor.",
    ],
    related: ["lore-faction-great-lakes-union"],
  },
  {
    id: "lore-state-michigan",
    title: "Michigan — The Motor Remnant",
    category: "world",
    tags: ["michigan", "state", "rust-belt", "detroit"],
    summary: "Detroit's state: the motor city rebuilt, the lakes, and the upper peninsula wilds.",
    body: [
      "Michigan is two peninsulas and one legend. The lower peninsula holds Detroit — the Motor City, bankrupt and reborn, the place that built the continent's cars and is now building its machines. The upper peninsula is forest, ore, and emptiness — the wildest country east of the Mississippi. The lakes surround everything: Michigan is a water state that thinks it's a car state.",
      "Detroit's peoples are the great migration made permanent. Black families from the South built the city's culture — the music, the churches, the political power — and held it together through the bankruptcy. Arab communities in Dearborn — the largest Arab-American concentration on the continent — run businesses that span the globe. Polish and Irish neighborhoods keep the old parish identities. The new immigrants — Bangladeshi in Hamtramck, Mexican in Southwest — work the factories that never fully closed.",
      "The city's comeback is the state's story: from bankruptcy to the continent's maker capital, one workshop at a time. The old auto plants became fabrication hubs. The engineers stayed. The culture — blunt, creative, unimpressed by coastal pretension — became an asset. Detroit doesn't ask for respect anymore; it builds things and lets the work speak.",
      "In the trade network, Michigan is the northern industrial hub: Detroit anchors the I-80's eastern end and the Great Lakes trade. Manufactured goods, machine parts, and vehicles flow south and west. The lakes still move bulk cargo — the old ore boats run with new crews. A caravan running the Michigan road deals with winter, the continent's toughest makers, and merchants who can smell a bad deal through a snowstorm.",
    ],
    related: ["lore-faction-great-lakes-union"],
  },
  {
    id: "lore-state-tennessee",
    title: "Tennessee — The Volunteer Corridor",
    category: "world",
    tags: ["tennessee", "state", "south", "music"],
    summary: "Music, mountains, and the Mississippi — the South's cultural heart and logistics spine.",
    body: [
      "Tennessee is the South's spine: Memphis on the Mississippi, Nashville in the middle, Knoxville in the east, and the music running through all of it like a current. The state's identity is sound — blues, country, rock, soul — and its economy is movement: the highways, the river, the distribution hubs that make the Southeast work.",
      "The peoples of Tennessee are the southern story in three cities. Memphis is Black culture at its deepest — the blues, the churches, Stax and Sun, the neighborhoods that made American music. Nashville is the industry town — country music's capital, but also the Kurdish capital of America (the largest Kurdish community on the continent), the university town, the healthcare hub. East Tennessee is Appalachian — the hillfolk, the old families, the codes of the mountains.",
      "The state's politics balance the three stars on the flag: west, middle, east, each with its own logic. Memphis looks to the river and the Delta. Nashville looks to the industry and the nation. Knoxville looks to the mountains and the old frontier. A trader who plays the cities against each other does well; a trader who picks one star over the others gets burned.",
      "For traders, Tennessee is the southern interchange: Memphis anchors the Mississippi river trade and the I-40 corridor, Nashville sits at the crossroads of I-65 and I-40. Goods moving between the Southeast, the Midwest, and Texas pass through Tennessee's highways. A caravan running the Tennessee road carries music in its ears and guards on its wagons — the corridor is rich, which means it's watched.",
    ],
    related: ["lore-faction-southern-compact"],
  },
  {
    id: "lore-state-nevada",
    title: "Nevada — The Silver Neon",
    category: "world",
    tags: ["nevada", "state", "desert", "vegas"],
    summary: "Las Vegas and the empty desert — the continent's casino, warehouse, and secret base.",
    body: [
      "Nevada is Las Vegas and everything else. The city is the continent's playground — the Strip rebuilt, the casinos running, the entertainment capital drawing visitors from every state. Everything else is desert: the test ranges, the mines, the small towns that serve the highways, and the empty basins where the government used to do things it didn't talk about.",
      "The peoples of Nevada are a desert boomtown mix. The casino workers — dealers, performers, servers — come from everywhere and form the city's working class. The Mormon ranching families of the north run the cattle country on old codes. The Basque sheepherders, descendants of 19th-century immigrants, still run sheep in the high desert. The tribal nations — the Paiute, Shoshone, Washoe — hold lands the state needs and negotiate hard. And the tech exiles, priced out of California, build data centers in the desert and call it the future.",
      "Vegas runs on a simple principle: the house always wins, and the house is the city. The casino families — the old names, updated for the new economy — control the Strip, the water, and the politics. The city's libertarian streak is real: low taxes, loose laws, and a live-and-let-live attitude that draws everyone the other states don't want. A trader in Vegas learns the odds or loses the stake.",
      "In the trade network, Nevada is the western warehouse: the I-15 corridor connects Vegas to California, and the city's distribution hubs serve the whole Southwest. Goods flow through Vegas — legal, gray, and otherwise. A caravan running the Nevada road deals with desert, distance, and the continent's most creative merchants. The house always wins, but the caravan doesn't have to play the house's game.",
    ],
    related: ["lore-faction-pacific-compact"],
  },
  {
    id: "lore-state-north-carolina",
    title: "North Carolina — The Research Triangle",
    category: "world",
    tags: ["north-carolina", "state", "south", "research"],
    summary: "Universities, tech, and tobacco roads — the New South's brain.",
    body: [
      "North Carolina is the New South's research lab: the Triangle — Raleigh, Durham, Chapel Hill — with its universities and tech campuses, Charlotte with its banks, and the old tobacco and textile towns reinventing themselves in between. The state's motto could be 'we're working on it' — and it usually works.",
      "The peoples of North Carolina are a southern crossroads. Black communities — descendants of the enslaved, builders of the churches and the colleges — anchor the state's culture and politics. White North Carolinians split between the old rural families and the suburban newcomers drawn by the jobs. The new immigrants — Mexican farmworkers turned citizens, Vietnamese fishing families on the coast, South Asian tech workers in the Triangle — keep the state's economy growing. The Lumbee and other tribal nations hold the southeastern counties on their own terms.",
      "The Triangle's logic is brains: the universities produce the researchers, the researchers produce the companies, the companies produce the jobs that draw the newcomers. Charlotte's logic is money: the banks that survived every crisis run the Southeast's finance. The old mill towns' logic is making things — furniture, textiles, tobacco — updated for the new economy. A trader who understands all three North Carolinas can sell anything to anyone.",
      "For traders, North Carolina is the southeastern research hub: the I-95 corridor passes through, and the state's markets connect the Northeast to the Deep South. Pharmaceuticals, tech, and manufactured goods flow north and south. A caravan running the Carolina road deals with the continent's most educated merchants — and its most polite negotiators, which is not the same as its softest.",
    ],
    related: ["lore-faction-atlantic-corridor", "lore-faction-southern-compact"],
  },
];
