/**
 * Codex entries for the Rowan solo-task systems (espionage, economy,
 * diplomacy, onboarding). Each entry carries a `mechanic:<slug>` tag so
 * the coverage audit (audit.ts) can verify every system is documented.
 */

import type { CodexEntry } from "./types.js";

function e(
  id: string,
  title: string,
  category: CodexEntry["category"],
  summary: string,
  body: string[],
  tags: string[],
  related: string[] = [],
): CodexEntry {
  return { id, title, category, summary, body, tags, related };
}

export const SOLO_ENTRIES: CodexEntry[] = [
  e("mechanic-scheme-timeline", "Scheme timeline", "campaign",
    "Watch a scheme's four stages fill up, with an ETA on completion.",
    ["Schemes move through Planning, Infiltration, Execution, and Exfiltration. The timeline shows each stage's completion so you can see where a scheme stalls.", "The ETA counts down from remaining progress and the scheme's rate. A scheme with no rate is stalled — feed it resources or call it off."],
    ["schemes", "espionage", "mechanic:scheme-timeline"], []),
  e("mechanic-blackmail-leverage", "Blackmail leverage", "campaign",
    "Leverage points per target; unused dirt decays each season.",
    ["Every secret you hold on a target adds leverage points. Spend them to force compliance — votes, gold, silence.", "Leverage decays with disuse: old dirt loses its sting. Strike while the iron is hot."],
    ["blackmail", "leverage", "espionage", "mechanic:blackmail-leverage"], []),
  e("mechanic-assassination", "Assassination", "campaign",
    "Poison, duel, or ambush — each with its own risks.",
    ["Poison is slow and deniable; duels are honorable but public; ambushes are brutal and fast.", "Skill raises your odds. Failure can expose you — and exposure has consequences."],
    ["assassination", "espionage", "mechanic:assassination"], []),
  e("mechanic-spy-extraction", "Spy extraction", "campaign",
    "Pull a compromised spy out before the post's heat burns them.",
    ["Extraction odds come from your team's skill against the post's heat, shown before you commit.", "A failed extraction loses the spy. Sometimes the kindest cut is to leave them."],
    ["extraction", "spies", "espionage", "mechanic:spy-extraction"], []),
  e("mechanic-spy-alerts", "Enemy spy alerts", "campaign",
    "When counter-espionage spots an enemy spy, choose: arrest, turn, or watch.",
    ["Arrest is safe but teaches you nothing. Turning a spy into a double agent is lucrative and risky.", "Watching lets you feed false intel for months — the slow, deniable play."],
    ["counter-espionage", "spies", "mechanic:spy-alerts"], []),
  e("mechanic-spy-tips", "Spy tutorial tips", "campaign",
    "First-time tips for each spy action, shown once and dismissed forever.",
    ["The first time you place a spy, sweep a post, or plan a scheme, a tip explains the stakes.", "Dismissed tips stay dismissed — reset them in settings if you want a refresher."],
    ["tutorial", "hints", "mechanic:spy-tips"], []),
  e("mechanic-workshop-pnl", "Workshop P&L", "economy",
    "Per-workshop profit and loss, season by season.",
    ["Every workshop keeps a ledger: income and costs per season, with totals and a verdict.", "A workshop that bleeds coin season after season should be improved — or sold."],
    ["workshops", "profit", "mechanic:workshop-pnl"], []),
  e("mechanic-caravan-ranking", "Caravan rankings", "economy",
    "Candidate routes ranked by profit per day.",
    ["The ranking prices every candidate route and sorts best-first, so the obvious choice is at the top.", "Profit per day beats raw profit: a short, fast route often out-earns a long haul."],
    ["caravans", "trade routes", "mechanic:caravan-ranking"], []),
  e("mechanic-price-alerts", "Price alerts", "economy",
    "Set a target price; get notified when the market hits it.",
    ["Set above-targets to know when to sell, below-targets to know when to buy.", "Fired alerts are consumed — set a new one if you want to catch the next swing."],
    ["market", "prices", "trade", "mechanic:price-alerts"], []),
  e("mechanic-tax-policy", "Tax simulator", "economy",
    "Preview a tax rate's income and unrest before you apply it.",
    ["Higher taxes earn more but breed unrest — and unrest grows quadratically past the fair rate.", "Simulate first: a rate that fills the treasury and empties the streets is a bad trade."],
    ["taxes", "unrest", "mechanic:tax-policy"], []),
  e("mechanic-smuggling-risk", "Smuggling risk", "economy",
    "See interception odds and expected value before a smuggling run.",
    ["The calculator weighs patrol strength against your stealth and shows the expected value.", "A run with negative expected value is a donation to the town watch. Don't."],
    ["smuggling", "contraband", "mechanic:smuggling-risk"], []),
  e("mechanic-trade-deals", "Trade agreements", "economy",
    "Propose deals to towns; the town AI accepts, counters, or refuses.",
    ["Offer coin and discounts, ask for tariff relief and market access.", "Goodwill decides: relationship, generosity, and the greed of your ask. Middling deals draw counters."],
    ["trade", "diplomacy", "mechanic:trade-deals"], []),
  e("mechanic-shortages", "Shortage warnings", "economy",
    "Supply shortfalls for garrison and army, flagged before the shelves are bare.",
    ["Each resource shows seasons of coverage left. Out means the army goes hungry this season.", "Stock up when warnings turn amber — red means it is already too late."],
    ["supplies", "garrison", "mechanic:shortages"], []),
  e("mechanic-treasury-forecast", "Treasury forecast", "economy",
    "A 30-day projection of the treasury from income and expense lines.",
    ["Day-by-day balances show exactly when the money runs out, if it does.", "The sparkline is the shape of your finances: climbing, flat, or falling off a cliff."],
    ["treasury", "forecast", "mechanic:treasury-forecast"], []),
  e("mechanic-loans", "Loans", "economy",
    "Borrow from moneylenders, repay with interest — or default and face the collectors.",
    ["Interest accrues every season. Repay in full to settle; overpayments come back as change.", "Default and collectors seize half the principal immediately — and no lender will touch you again."],
    ["loans", "debt", "mechanic:loans"], []),
  e("mechanic-trade-dominance", "Trade dominance", "economy",
    "Your share of all trade, marching toward economic victory.",
    ["Control 60% of trade and the economy is yours — the markets answer to you.", "The progress bar is the campaign in miniature: every route, every deal, every season."],
    ["victory", "trade", "mechanic:trade-dominance"], []),
  e("mechanic-relation-notifications", "Relation changes", "campaign",
    "Every relation change shows its reason.",
    ["Gifts, raids, betrayals, marriages — each shift in standing names its cause.", "The notification feed is your diplomatic memory. Read it before you act."],
    ["relations", "diplomacy", "mechanic:relation-notifications"], []),
  e("mechanic-treaties", "Treaty compliance", "campaign",
    "Every treaty term listed with its compliance status.",
    ["Terms are marked kept, broken, or pending for each party.", "A treaty with broken terms is under strain — fix it or prepare for it to collapse."],
    ["treaties", "diplomacy", "mechanic:treaties"], []),
  e("mechanic-war-goals", "War goals", "campaign",
    "Declare why you fight; the goal shapes how fast the war exhausts you.",
    ["Conquest, liberation, tribute, humiliation — each exhausts at its own pace.", "Wars fought for a declared goal wear slower than aimless ones. Declare, or burn out fast."],
    ["war", "weariness", "mechanic:war-goals"], []),
  e("mechanic-peace-concessions", "Peace terms", "campaign",
    "Slide your offer and demands; watch the AI's acceptance odds live.",
    ["Coin, towns, tribute — offer and demand, and the odds update as you slide.", "Winning the war and exhausting the enemy both help. Greedy demands insult them."],
    ["peace", "negotiation", "mechanic:peace-concessions"], []),
  e("mechanic-joint-operations", "Joint operations", "campaign",
    "Coordinate attacks with allies: axes, seasons, and combined force.",
    ["Pick the target, the season, each side's force, and the axis of attack.", "The force ratio tells you the truth: overwhelming, or thin. Plan accordingly."],
    ["allies", "war", "mechanic:joint-operations"], []),
  e("mechanic-tribute", "Tribute", "campaign",
    "Suggested tribute from the power differential.",
    ["The stronger side collects; the weaker side pays to buy peace.", "Balanced powers owe each other nothing — tribute is the price of weakness."],
    ["tribute", "diplomacy", "mechanic:tribute"], []),
  e("mechanic-reputation", "Diplomatic reputation", "campaign",
    "A visible 0–100 meter of your standing, moved by your acts.",
    ["Keep treaties and honor deals to climb; betray allies and sack towns to fall.", "Reputation drifts toward neutral over quiet seasons — but Oathbreaker is a long shadow."],
    ["reputation", "honor", "mechanic:reputation"], []),
  e("mechanic-envoy-assignment", "Envoy assignment", "campaign",
    "Assign skilled envoys to negotiations to shorten them.",
    ["Each point of persuasion skill cuts a round off the negotiation.", "An envoy can only serve one negotiation at a time — recall them when done."],
    ["envoys", "negotiation", "mechanic:envoy-assignment"], []),
  e("mechanic-border-incidents", "Border incidents", "campaign",
    "Skirmishes and seized caravans offer three responses: retaliate, protest, or overlook.",
    ["Retaliation hurts relations and risks war. Protest is measured. Overlooking calms — but looks weak.", "There is no safe answer, only the one you can live with."],
    ["borders", "incidents", "mechanic:border-incidents"], []),
  e("mechanic-great-powers", "Great power ranking", "campaign",
    "Clans ranked by composite power: troops, towns, treasury, reputation.",
    ["One score per clan, ranked best-first with the gap to the leader.", "Know where you stand — and who to fear, court, or topple."],
    ["ranking", "power", "mechanic:great-powers"], []),
  e("mechanic-battle-tutorial", "Battle tutorial", "command",
    "An interactive tutorial for battle orders and the camera.",
    ["Six steps: select, move, attack, pan, rotate, zoom. Do each one to advance.", "Skip any step you already know. The tutorial tracks your progress."],
    ["tutorial", "battle", "mechanic:battle-tutorial"], []),
  e("mechanic-hint-cooldown", "Hint cooldowns", "command",
    "Hints never repeat within ten minutes.",
    ["Each hint cools down after showing, so the game stops nagging.", "Cooldowns survive reloads — patience is enforced."],
    ["hints", "tutorial", "mechanic:hint-cooldown"], []),
];
