import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { snapshotProblem } from "./provider.js";

// Cross-language contract test (Task 96): a real snapshot built by the Go
// apiserver must pass the TypeScript decoder's validator. The fixture file is
// generated by TestExportSnapshotForTsDecoder in the sim's apiserver tests.
describe("Go snapshot through TS decoder", () => {
  it("passes validation with no problems", () => {
    const dir = dirname(fileURLToPath(import.meta.url));
    const raw = readFileSync(join(dir, "__fixtures__", "go-snapshot.json"), "utf-8");
    const snap = JSON.parse(raw);
    const problem = snapshotProblem(snap);
    expect(problem).toBeNull();
  });

  it("has the villages and notifications blocks the client reads", () => {
    const dir = dirname(fileURLToPath(import.meta.url));
    const raw = readFileSync(join(dir, "__fixtures__", "go-snapshot.json"), "utf-8");
    const snap = JSON.parse(raw) as Record<string, unknown>;
    expect(Array.isArray(snap["villages"])).toBe(true);
    expect(Array.isArray(snap["notifications"])).toBe(true);
    expect((snap["villages"] as unknown[]).length).toBeGreaterThan(0);
    expect((snap["notifications"] as unknown[]).length).toBeGreaterThan(0);
  });
});
