"""Blender step: decimate the close-tier mesh down to a triangle budget, preserving skin weights.

Run by tools/build-assets.mjs as:
    blender --background --factory-startup --python tools/blender/decimate.py -- \
        <in.obj> <in_weights.json> <out.obj> <out_weights.json> <target_tris> <joint_names_csv>

Blender's decimate modifier is a quadric error metric collapse, which is the right tool for an LOD
tier: it preserves the silhouette and drops interior detail. It interpolates vertex-group weights
during each collapse, which is what keeps the mesh skinned, so the weights are read back off the
evaluated mesh rather than carried over by index.

Output is OBJ plus a JSON sidecar, because OBJ carries no skinning. Vertex order is preserved
through the modifier, so the caller can match by position if it needs to.
"""

import json
import sys

import bpy


def log(*a):
    print(" ".join(str(x) for x in a), flush=True)


def main() -> int:
    argv = sys.argv[sys.argv.index("--") + 1 :]
    in_obj, in_weights, out_obj, out_weights, target_tris, joints_csv = argv[:6]
    joints = joints_csv.split(",")

    bpy.ops.wm.read_factory_settings(use_empty=True)
    bpy.ops.wm.obj_import(filepath=in_obj)
    ob = [o for o in bpy.data.objects if o.type == "MESH"][0]
    before = sum(len(p.vertices) - 2 for p in ob.data.polygons)
    before_v = len(ob.data.vertices)

    # Skin has to exist before the collapse for the weights to be interpolated rather than dropped.
    groups = [ob.vertex_groups.new(name=j) for j in joints]
    src = json.load(open(in_weights))["verts"]
    for entry in src:
        for j, w in entry["p"]:
            if w > 1e-4 and 0 <= j < len(groups):
                groups[j].add([entry["v"]], float(w), "REPLACE")

    ratio = min(1.0, int(target_tris) / before)
    mod = ob.modifiers.new("dec", "DECIMATE")
    mod.ratio = ratio
    mod.use_collapse_triangulate = True

    dg = bpy.context.evaluated_depsgraph_get()
    ev = ob.evaluated_get(dg)
    me = ev.to_mesh()

    after = sum(len(p.vertices) - 2 for p in me.polygons)
    nvert = len(me.vertices)
    ngroup = len(ob.vertex_groups)
    gindex = {g.index: g.name for g in ob.vertex_groups}

    with open(out_obj, "w") as fh:
        fh.write("# generated by tools/blender/decimate.py\n")
        for v in me.vertices:
            fh.write(f"v {v.co.x:.6f} {v.co.y:.6f} {v.co.z:.6f}\n")
        for v in me.vertices:
            fh.write(f"vn {v.normal.x:.6f} {v.normal.y:.6f} {v.normal.z:.6f}\n")
        for p in me.polygons:
            vs = list(p.vertices)
            if len(vs) < 3:
                continue
            for k in range(1, len(vs) - 1):
                a, b, c = vs[0] + 1, vs[k] + 1, vs[k + 1] + 1
                fh.write(f"f {a}//{a} {b}//{b} {c}//{c}\n")

    # Weights come back keyed by joint name, not index, so the caller is not tied to this order.
    per_vert = []
    unweighted = 0
    for v in me.vertices:
        pairs = []
        for g in v.groups:
            if g.weight > 1e-4:
                pairs.append([gindex.get(g.group, joints[0]), round(float(g.weight), 5)])
        pairs.sort(key=lambda x: -x[1])
        pairs = pairs[:4]
        if not pairs:
            unweighted += 1
            pairs = [["pelvis", 1.0]]
        per_vert.append(pairs)
    ev.to_mesh_clear()

    with open(out_weights, "w") as fh:
        json.dump({"joints": joints, "verts": per_vert}, fh)

    log(f"DECIMATE in_tris={before} in_verts={before_v} out_tris={after} out_verts={nvert} "
        f"ratio={ratio:.4f} groups={ngroup} unweighted={unweighted}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
