/**
 * The stylesheet, generated from `tokens.ts`.
 *
 * `CONSTITUTION.md` section 3.4 says components do not introduce their own palette
 * or fonts. The way that is enforced rather than merely intended: this module is the
 * only thing that writes CSS custom properties, the file on disk is produced from
 * it, and `__tests__/tokens-css.test.ts` regenerates it and fails if the committed
 * file differs by a single character.
 */

import {
  breakpoints,
  font,
  paper,
  ink,
  accent,
  subtitle,
  status,
  radius,
  sheet,
  space,
  type,
  terrainBands,
  mapColor,
  focusRing,
  paperTreatment,
  STAMP_ROTATION_DEG,
} from "./index.js";
import fontManifest from "../../assets/fonts/FONT-MANIFEST.json";

function typeVars(): string {
  return Object.entries(type)
    .map(([name, t]) => {
      const family = t.family === "mono" ? "var(--font-mono)" : "var(--font-sans)";
      return [
        `  --type-${kebab(name)}-size: ${t.size}px;`,
        `  --type-${kebab(name)}-line: ${t.line}px;`,
        `  --type-${kebab(name)}-weight: ${t.weight};`,
        `  --type-${kebab(name)}-tracking: ${t.tracking};`,
        `  --type-${kebab(name)}-family: ${family};`,
        ...('uppercase' in t ? [`  --type-${kebab(name)}-transform: uppercase;`] : []),
      ].join("\n");
    })
    .join("\n");
}

function kebab(s: string): string {
  return s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

/**
 * The @font-face rules, built from the fetched font manifest so a font can never be
 * referenced without its file, and a file can never ship without a licence. The
 * manifest is generated by tools/fetch-fonts.mjs alongside the binaries.
 */
function fontFaces(): string {
  const lines: string[] = [
    "/* Typefaces, from assets/fonts/FONT-MANIFEST.json. Both SIL Open Font License 1.1;",
    " * licence copies in assets/fonts/licences/. Self-hosted: no third-party request. */",
    "",
  ];
  for (const entry of fontManifest.files) {
    const weights = [...entry.weights].sort((a, b) => a - b);
    lines.push(
      "@font-face {",
      `  font-family: '${entry.family}';`,
      `  font-style: ${entry.style};`,
      `  font-weight: ${weights.length > 1 ? `${weights[0]} ${weights[weights.length - 1]}` : weights[0]};`,
      "  font-display: swap;",
      // The manifest records the repo path; the browser wants the served path.
      `  src: url('/${entry.file.replace(/^public\//, "")}') format('woff2');`,
      "}",
      "",
    );
  }
  return lines.join("\n");
}

export function tokensCss(): string {
  const paperFibre = `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='180' height='180'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='3'/%3E%3C/filter%3E%3Crect width='180' height='180' filter='url(%23n)' opacity='1'/%3E%3C/svg%3E")`;

  return `/* GENERATED from src/design/tokens.ts. Do not hand-edit.
 *
 * tools/build-tokens.mjs writes this file and
 * src/design/__tests__/tokens-css.test.ts fails if it drifts. The locked direction
 * is clients/campaign/ART_DIRECTION.md. */

${fontFaces()}
:root {
  /* Paper is the substrate; ink is the type on it. Warm throughout. */
${Object.entries(paper)
  .map(([k, v]) => `  --paper-${k}: ${v};`)
  .join("\n")}

${Object.entries(ink)
  .map(([k, v]) => `  --ink-${k}: ${v};`)
  .join("\n")}

  --accent-primary: ${accent.primary};
  --accent-primary-deep: ${accent.primaryDeep};
  --accent-primary-ink: ${accent.primaryInk};
  --accent-influence: ${accent.influence};
  --accent-influence-ink: ${accent.influenceInk};
  --accent-info: ${accent.info};
  --accent-info-ink: ${accent.infoInk};

  /* Subtitle bar colours (task 21): captions over the 3D scene. */
  --subtitle-text: ${subtitle.text};
  --subtitle-speaker: ${subtitle.speaker};
  --subtitle-background-translucent: ${subtitle.backgroundTranslucent};
  --subtitle-background-solid: ${subtitle.backgroundSolid};

${Object.entries(status)
  .map(
    ([k, v]) =>
      [
        `  --status-${k}: ${v.mark};`,
        `  --status-${k}-mark: ${v.mark};`,
        `  --status-${k}-fill: ${v.fill};`,
        `  --status-${k}-ink: ${v.ink};`,
        `  --status-${k}-glyph: "${v.glyph}";`,
      ].join("\n"),
  )
  .join("\n")}

${Object.entries(space)
  .map(([k, v]) => `  --space-${k}: ${v}px;`)
  .join("\n")}

${Object.entries(radius)
  .map(([k, v]) => `  --radius-${k}: ${v};`)
  .join("\n")}

${Object.entries(sheet)
  .map(([k, v]) => `  --sheet-${k}: ${v};`)
  .join("\n")}

  --font-sans: ${font.sans};
  --font-mono: ${font.mono};
  --focus-ring: ${focusRing};
  --stamp-rotation: ${STAMP_ROTATION_DEG}deg;
  --paper-fibre: ${paperFibre};
  --paper-fibre-opacity: ${paperTreatment.fibreOpacity};
  --well-inset: ${paperTreatment.wellInset};

  /* Terrain ramp: hypsometric, keyed to elevation, desaturated by construction. */
${terrainBands
  .map(
    (b, i) =>
      `  --terrain-${i}: ${b.color}; /* ${b.name}, under ${b.upTo === Infinity ? "3600" : b.upTo} m */`,
  )
  .join("\n")}
  --map-water: ${mapColor.water};
  --map-sky: ${mapColor.sky};
  --map-fog: ${mapColor.fog};
  --road-major: ${mapColor.roadMajor};
  --road-minor: ${mapColor.roadMinor};
  --rail: ${mapColor.rail};

${typeVars()}

  /* Breakpoints, as custom properties for the JS layout switches. */
  --bp-wide: ${breakpoints.wide}px;
  --bp-desktop: ${breakpoints.desktop}px;
  --bp-tablet: ${breakpoints.tablet}px;
}

/* UI scale, from the 80 / 90 / 100 / 115 / 130 / 150 percent setting (task 17).
   Every type and space token is in rem or px off this root, so this is the one
   switch that has to exist. */
html[data-ui-scale="80"]  { font-size: 80%; }
html[data-ui-scale="90"]  { font-size: 90%; }
html[data-ui-scale="100"] { font-size: 100%; }
html[data-ui-scale="115"] { font-size: 115%; }
html[data-ui-scale="130"] { font-size: 130%; }
html[data-ui-scale="150"] { font-size: 150%; }

* { box-sizing: border-box; }

html, body {
  margin: 0;
  padding: 0;
  height: 100%;
  background: var(--ink-900);
  color: var(--ink-900);
  font-family: var(--font-sans);
  -webkit-font-smoothing: antialiased;
  /* No page-level horizontal scroll at any width, including 320px. */
  overflow-x: hidden;
}

/* A panel is a sheet of paper lying on the map. Paper fibre over the fill, a hairline
   rule outside, a highlight inside the top edge. Never a frosted card. */
.sheet {
  position: relative;
  background-color: var(--paper-100);
  background-image: var(--paper-fibre);
  background-blend-mode: multiply;
  background-size: var(--paper-fibre-opacity);
  border: 1px solid var(--paper-300);
  box-shadow: var(--sheet-2);
  color: var(--ink-900);
  font-family: var(--font-sans);
  font-size: var(--type-body-size);
  line-height: var(--type-body-line);
}

.sheet::before {
  content: "";
  position: absolute;
  inset: 0 0 auto 0;
  height: 1px;
  background: var(--paper-000);
  pointer-events: none;
}

/* A form rule, as on a printed form. Used under every section header. */
.form-rule {
  height: 1px;
  background: var(--paper-300);
  border: 0;
  margin: var(--space-2) 0 var(--space-3);
}

.section-header {
  font-family: var(--font-sans);
  font-size: var(--type-section-size);
  line-height: var(--type-section-line);
  font-weight: var(--type-section-weight);
  letter-spacing: var(--type-section-tracking);
  text-transform: uppercase;
  color: var(--ink-500);
  display: flex;
  align-items: center;
  gap: var(--space-2);
}

.title {
  font-size: var(--type-title-size);
  line-height: var(--type-title-line);
  font-weight: var(--type-title-weight);
  letter-spacing: var(--type-title-tracking);
}

.display {
  font-size: var(--type-display-size);
  line-height: var(--type-display-line);
  font-weight: var(--type-display-weight);
  letter-spacing: var(--type-display-tracking);
}

.label {
  font-size: var(--type-label-size);
  line-height: var(--type-label-line);
  font-weight: var(--type-label-weight);
}

.caption {
  font-size: var(--type-caption-size);
  line-height: var(--type-caption-line);
  letter-spacing: var(--type-caption-tracking);
  color: var(--ink-500);
}

/* Every numeral in a table, gauge, ledger or cause chain is tabular mono. */
.data {
  font-family: var(--font-mono);
  font-size: var(--type-data-size);
  line-height: var(--type-data-line);
  font-weight: var(--type-data-weight);
  font-variant-numeric: tabular-nums;
}

.data-sm {
  font-family: var(--font-mono);
  font-size: var(--type-data-sm-size);
  line-height: var(--type-data-sm-line);
  font-variant-numeric: tabular-nums;
  color: var(--ink-500);
}

.data-lg {
  font-family: var(--font-mono);
  font-size: var(--type-data-lg-size);
  line-height: var(--type-data-lg-line);
  font-weight: var(--type-data-lg-weight);
  font-variant-numeric: tabular-nums;
}

button, input, select {
  font-family: inherit;
  font-size: inherit;
  color: inherit;
}

button {
  cursor: pointer;
  border-radius: var(--radius-1);
}

:focus-visible {
  outline: none;
  box-shadow: var(--focus-ring);
}

.visually-hidden {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0 0 0 0);
  white-space: nowrap;
  border: 0;
}

/* Reduced motion: UI_UX.md section 12. The skeleton wash, the grain animation and
   camera easing all read this. */
@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.001ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.001ms !important;
  }
}
`;
}
