"""Build the client wire notables file for the playable region.

Reads the full notables export (services/world-data/exports/notables.jsonl.gz),
keeps only the playable settlements listed in
clients/campaign/public/world/settlements.json, and writes
clients/campaign/public/world/notables.json in the wire envelope format the
campaign client loads at boot.

Unlike the first version of this script, it does NOT re-synthesize notables
from constant placeholder state. The export rows were generated by the
pipeline from real settlement data (population, prosperity, food stocks,
unrest, loyalty, infection), so filtering the export keeps every notable
derived from its town's actual condition.

The export stores quest_types / grievances / recruit_pool as JSON-encoded
strings (the published schema's type vocabulary is scalars only); they are
decoded back to native values here because the wire file is consumed by the
TypeScript client, not the schema.

All paths are resolved from this file's location, so the script runs from any
checkout with no absolute paths:

    python services/world-data/tools/build-wire-notables.py
"""

from __future__ import annotations

import gzip
import json
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
EXPORT = REPO_ROOT / "services/world-data/exports/notables.jsonl.gz"
WIRE_SETTLEMENTS = REPO_ROOT / "clients/campaign/public/world/settlements.json"
WIRE_NOTABLES = REPO_ROOT / "clients/campaign/public/world/notables.json"

# Export columns stored as JSON-encoded strings; decoded for the wire client.
JSON_COLUMNS = ("quest_types", "grievances", "recruit_pool")


def iter_export_rows(path: Path):
    """Yield data rows, skipping the metadata header line the exporter writes."""
    with gzip.open(path, "rt", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            row = json.loads(line)
            if isinstance(row, dict) and row.get("_header"):
                continue
            yield row


def main() -> None:
    if not EXPORT.is_file():
        raise SystemExit(
            f"export not found: {EXPORT}\n"
            "Run the world-data pipeline first "
            "(python -m worlddata run --skip-fetch --skip-postgres)."
        )
    wire = json.loads(WIRE_SETTLEMENTS.read_text(encoding="utf-8"))
    playable = {s["osmId"] for s in wire["settlements"]}

    kept: list[dict] = []
    for row in iter_export_rows(EXPORT):
        if row.get("settlement_id") not in playable:
            continue
        out = dict(row)
        for column in JSON_COLUMNS:
            value = out.get(column)
            if isinstance(value, str):
                out[column] = json.loads(value)
        kept.append(out)

    missing = playable - {r["settlement_id"] for r in kept}
    envelope = {
        "source": ("world-data notables pipeline (QUESTS_AND_NOTABLES.md s2); "
                   "rows generated from real settlement state, fictional persons"),
        "licence": ("Generated content; names fictional by construction, "
                    "never sourced from real-person lists."),
        "retrieved": date.today().isoformat(),
        "notables": kept,
    }
    WIRE_NOTABLES.write_text(json.dumps(envelope), encoding="utf-8")
    print(f"{len(kept)} notables for {len(playable)} playable settlements -> {WIRE_NOTABLES}")
    if missing:
        print(f"WARNING: {len(missing)} playable settlements have no notables: "
              f"{sorted(missing)[:5]}")


if __name__ == "__main__":
    main()
