"""Regenerate tools/anim/CLIPS.md from the bake sidecar.

The clip manifest is never hand-edited: this module reads dist/anim_bones.json
(written by the bake) and rewrites CLIPS.md from it, so the published catalog
cannot drift from what the pipeline actually produced.
"""

import json
from pathlib import Path


def render(sidecar):
    lines = [
        "# Animation clip manifest",
        "",
        "Regenerated by the animation pipeline (`python3 tools/anim/run.py`).",
        "Do not edit by hand; it is rewritten on every pipeline run.",
        "",
        f"Texture: `dist/anim_bones.bin` ({sidecar['width']}x{sidecar['height']} "
        f"RGBA16F, sha256 `{sidecar['sha256'][:16]}...`)",
        f"Skeleton: `{sidecar['skeleton']}` "
        f"({sidecar['joint_count']} joints, {sidecar['fps']} fps bake)",
        f"Decode bar: max relative error {sidecar['decode_bar']:.2e} per texel; "
        f"measured {sidecar['max_decode_rel_err']:.2e}.",
        "",
        "| Clip | Duration | Loop | Bones | Root motion | License | Source |",
        "|---|---|---|---|---|---|---|",
    ]
    for name, c in sidecar["clips"].items():
        lines.append(
            f"| {name} | {c['duration_s']:.2f} s | "
            f"{'yes' if c['loop'] else 'no'} | {sidecar['joint_count']} | "
            f"{c['root_policy']} | {c['license']} | {c['source']} |"
        )
    lines += [
        "",
        "## Clip notes",
        "",
        "* **attack / shoot / hit-react / death** are extracted from the "
        "Quaternius SWAT model (CC0) and retargeted onto the shared skeleton.",
        "* **idle / walk / run** are retargeted from the three.js Soldier.glb "
        "(MIT, Mixamo rig). `*-proc` are the procedural fallbacks with the "
        "same names; the game uses the retargeted clip when present and the "
        "procedural one when a model ships without source animation.",
        "* **block / knockdown / crouch / aim-pose** are fully procedural: "
        "no source asset, no license to clear, bit-exact loops where marked.",
        "* One-shot clips (attack, shoot, block, hit-react, death, knockdown) "
        "start and end in the neutral stance; death holds its final frame in "
        "the game via the last baked row.",
        "* Root motion: locomotion loops are baked in-place (the sim drives "
        "position); one-shots keep authored root motion so falls read "
        "correctly.",
        "",
    ]
    return "\n".join(lines)


def regenerate(anim_dir):
    anim_dir = Path(anim_dir)
    sidecar = json.loads((anim_dir / "dist" / "anim_bones.json").read_text())
    out = anim_dir / "CLIPS.md"
    out.write_text(render(sidecar))
    return out
