"""Procedural animation clips: the zero-licensing fallback set.

Every clip here is synthesized from closed-form joint-angle curves, so there
is no source asset and no license to clear. Loop clips are bit-exact loops:
the pose is a sum of sinusoids with integer cycle counts over the clip
duration, so frame N-1 flows into frame 0 with no pop. One-shots start and end
in the neutral stance.

Conventions: angles are radians, XYZ euler order, applied as local joint
rotations on the shared skeleton. Y-up, metres. "root" entries are root
translation offsets from the bind pose.
"""

import math

import numpy as np

from extract import Clip, FPS

LICENSE = "generated by tools/anim/procedural.py; no source asset, no license needed"
SOURCE = "procedural (tools/anim/procedural.py)"

IDENTITY = (0.0, 0.0, 0.0)
TAU = 2.0 * math.pi


def _qx(a):
    return np.array([math.sin(a / 2), 0.0, 0.0, math.cos(a / 2)])


def _qy(a):
    return np.array([0.0, math.sin(a / 2), 0.0, math.cos(a / 2)])


def _qz(a):
    return np.array([0.0, 0.0, math.sin(a / 2), math.cos(a / 2)])


def euler_to_quat(rx, ry, rz):
    """XYZ euler order as a unit quaternion (x, y, z, w)."""
    q = np.array([0.0, 0.0, 0.0, 1.0])
    for single in (_qx(rx), _qy(ry), _qz(rz)):
        q = _mul(q, single)
    return q


def _mul(a, b):
    ax, ay, az, aw = a
    bx, by, bz, bw = b
    return np.array([
        aw * bx + ax * bw + ay * bz - az * by,
        aw * by - ax * bz + ay * bw + az * bx,
        aw * bz + ax * by - ay * bx + az * bw,
        aw * bw - ax * bx - ay * by - az * bz,
    ])


def _smooth(u):
    u = max(0.0, min(1.0, u))
    return u * u * (3.0 - 2.0 * u)


def _snap(v):
    # sin(k*TAU) is ~1e-16, not 0. Snap sub-1e-12 values so loop clips are
    # bit-exact at t=duration, not just close.
    return 0.0 if abs(v) < 1e-12 else v


def _pose(curves, t):
    """curves: {joint: fn(t) -> (rx, ry, rz)}. Returns {joint: quat}."""
    out = {}
    for joint, fn in curves.items():
        if joint == "root":
            continue
        rx, ry, rz = (_snap(v) for v in fn(t))
        if rx or ry or rz:
            out[joint] = euler_to_quat(rx, ry, rz)
    return out


def _root(curves, t):
    fn = curves.get("root")
    if not fn:
        return np.zeros(3)
    return np.array([_snap(v) for v in fn(t)], dtype=np.float64)


def _build(name, duration, curves, loop, root_policy="in-place"):
    nframes = max(2, int(round(duration * FPS)))
    frames = []
    for i in range(nframes):
        t = (i / nframes) * duration if loop else (i / (nframes - 1)) * duration
        frames.append({"rot": _pose(curves, t), "root": _root(curves, t)})
    clip = Clip(name, frames, loop, SOURCE, LICENSE, root_policy)
    # Loop clips are periodic: wrap the probe time so sample_fn(duration)
    # lands exactly on sample_fn(0), bit-for-bit.
    clip.sample_fn = (lambda t: {"rot": _pose(curves, t % duration),
                                "root": _root(curves, t % duration)}
                      if loop else
                      lambda t: {"rot": _pose(curves, t), "root": _root(curves, t)})
    clip.exact_duration = duration
    return clip


def _build_keyframed(name, duration, keys, loop, root_policy="as-authored"):
    """keys: list of (time, {joint: (rx,ry,rz) | 'root': (x,y,z)})."""
    keys = sorted(keys, key=lambda k: k[0])

    def at(t):
        if t <= keys[0][0]:
            return keys[0][1]
        if t >= keys[-1][0]:
            return keys[-1][1]
        for (t0, p0), (t1, p1) in zip(keys, keys[1:]):
            if t0 <= t <= t1:
                u = _smooth((t - t0) / (t1 - t0))
                joints = set(p0) | set(p1)
                out = {}
                for j in joints:
                    a = p0.get(j, IDENTITY if j != "root" else (0.0, 0.0, 0.0))
                    b = p1.get(j, IDENTITY if j != "root" else (0.0, 0.0, 0.0))
                    out[j] = tuple(x + (y - x) * u for x, y in zip(a, b))
                return out
        return keys[-1][1]

    nframes = max(2, int(round(duration * FPS)))
    frames = []
    for i in range(nframes):
        t = (i / nframes) * duration if loop else (i / (nframes - 1)) * duration
        pose = at(t)
        rot = {j: euler_to_quat(*pose[j]) for j in pose
               if j != "root" and any(pose[j])}
        root = np.array(pose.get("root", (0.0, 0.0, 0.0)), dtype=np.float64)
        frames.append({"rot": rot, "root": root})
    clip = Clip(name, frames, loop, SOURCE, LICENSE, root_policy)

    def sample_fn(t):
        pose = at(t)
        return {"rot": {j: euler_to_quat(*pose[j]) for j in pose
                        if j != "root" and any(pose[j])},
                "root": np.array(pose.get("root", (0.0, 0.0, 0.0)), dtype=np.float64)}

    clip.sample_fn = sample_fn
    clip.exact_duration = duration
    return clip


# ---------------------------------------------------------------------------
# Loop clips (bit-exact: integer cycle counts over the duration).


def idle_proc(duration=2.4):
    c = {
        "spine_02": lambda t: (0.025 * math.sin(TAU * t / duration), 0, 0),
        "spine_03": lambda t: (0.02 * math.sin(TAU * t / duration + 0.6), 0, 0),
        "neck_01": lambda t: (0.015 * math.sin(TAU * t / duration + 1.2), 0, 0),
        "upperarm_l": lambda t: (0.03 * math.sin(TAU * t / duration + 0.3), 0,
                                 0.04 + 0.01 * math.sin(TAU * t / duration)),
        "upperarm_r": lambda t: (0.03 * math.sin(TAU * t / duration + 0.9), 0,
                                 -0.04 - 0.01 * math.sin(TAU * t / duration)),
        "root": lambda t: (0.0, 0.012 * math.sin(TAU * t / duration), 0.0),
    }
    return _build("idle-proc", duration, c, loop=True)


def walk_proc(duration=1.0):
    w = TAU / duration  # one full stride cycle per loop
    c = {
        "thigh_l": lambda t: (-0.55 * math.sin(w * t), 0, 0),
        "thigh_r": lambda t: (0.55 * math.sin(w * t), 0, 0),
        "calf_l": lambda t: (0.7 * max(0.0, math.sin(w * t + 0.6)), 0, 0),
        "calf_r": lambda t: (0.7 * max(0.0, -math.sin(w * t + 0.6)), 0, 0),
        "upperarm_l": lambda t: (0.38 * math.sin(w * t), 0, 0.06),
        "upperarm_r": lambda t: (-0.38 * math.sin(w * t), 0, -0.06),
        "lowerarm_l": lambda t: (-0.25 - 0.1 * math.sin(w * t), 0, 0),
        "lowerarm_r": lambda t: (-0.25 + 0.1 * math.sin(w * t), 0, 0),
        "spine_02": lambda t: (0.04, 0, 0.03 * math.sin(w * t)),
        "root": lambda t: (0.0, -0.035 + 0.035 * math.cos(2 * w * t), 0.0),
    }
    return _build("walk-proc", duration, c, loop=True)


def run_proc(duration=0.7):
    w = TAU / duration
    c = {
        "thigh_l": lambda t: (-0.85 * math.sin(w * t), 0, 0),
        "thigh_r": lambda t: (0.85 * math.sin(w * t), 0, 0),
        "calf_l": lambda t: (1.1 * max(0.0, math.sin(w * t + 0.7)), 0, 0),
        "calf_r": lambda t: (1.1 * max(0.0, -math.sin(w * t + 0.7)), 0, 0),
        "upperarm_l": lambda t: (0.55 * math.sin(w * t), 0, 0.08),
        "upperarm_r": lambda t: (-0.55 * math.sin(w * t), 0, -0.08),
        "lowerarm_l": lambda t: (-1.15, 0, 0),
        "lowerarm_r": lambda t: (-1.15, 0, 0),
        "spine_01": lambda t: (0.10, 0, 0),
        "spine_02": lambda t: (0.08, 0, 0.02 * math.sin(w * t)),
        "neck_01": lambda t: (-0.12, 0, 0),
        "root": lambda t: (0.0, -0.05 + 0.05 * math.cos(2 * w * t), 0.0),
    }
    return _build("run-proc", duration, c, loop=True)


def crouch(duration=2.0):
    base = {
        "thigh_l": (0.95, 0, 0.06), "thigh_r": (0.95, 0, -0.06),
        "calf_l": (-1.15, 0, 0), "calf_r": (-1.15, 0, 0),
        "foot_l": (0.25, 0, 0), "foot_r": (0.25, 0, 0),
        "spine_01": (0.18, 0, 0), "spine_02": (0.14, 0, 0),
        "neck_01": (-0.18, 0, 0),
        "upperarm_l": (0.25, 0, 0.12), "upperarm_r": (0.25, 0, -0.12),
        "lowerarm_l": (-0.5, 0, 0), "lowerarm_r": (-0.5, 0, 0),
        "root": (0.0, -0.38, 0.0),
    }
    w = TAU / duration
    c = {j: (lambda t, v=v: (v[0] + 0.02 * math.sin(w * t), v[1], v[2]))
         for j, v in base.items() if j != "root"}
    c["root"] = lambda t: (0.0, -0.38 + 0.012 * math.sin(w * t), 0.0)
    return _build("crouch", duration, c, loop=True)


def aim_pose(duration=2.0):
    # Rifle aim stance: right arm shouldered forward, left hand supporting,
    # slight crouch, head into the sights. Loops with a micro sway.
    base = {
        "upperarm_r": (-1.30, -0.15, -0.10),
        "lowerarm_r": (-0.55, 0, 0),
        "upperarm_l": (-1.05, 0.55, 0.15),
        "lowerarm_l": (-0.9, -0.5, 0),
        "spine_01": (0.10, 0.12, 0),
        "spine_02": (0.08, 0, 0),
        "neck_01": (-0.10, -0.08, 0),
        "thigh_l": (0.28, 0, 0.05), "thigh_r": (0.22, 0, -0.05),
        "calf_l": (-0.34, 0, 0), "calf_r": (-0.28, 0, 0),
        "root": (0.0, -0.13, 0.0),
    }
    w = TAU / duration
    c = {j: (lambda t, v=v: (v[0] + 0.015 * math.sin(w * t + 0.5), v[1], v[2]))
         for j, v in base.items() if j != "root"}
    c["root"] = lambda t: (0.0, -0.13 + 0.008 * math.sin(w * t), 0.0)
    return _build("aim-pose", duration, c, loop=True)


# ---------------------------------------------------------------------------
# One-shots (start and end in the neutral stance).


def block(duration=0.6):
    guard = {
        "upperarm_l": (-1.15, 0.35, 0.25), "upperarm_r": (-1.15, -0.35, -0.25),
        "lowerarm_l": (-1.5, -0.4, 0), "lowerarm_r": (-1.5, 0.4, 0),
        "thigh_l": (0.35, 0, 0.05), "thigh_r": (0.35, 0, -0.05),
        "calf_l": (-0.45, 0, 0), "calf_r": (-0.45, 0, 0),
        "spine_02": (0.16, 0, 0),
        "root": (0.0, -0.14, 0.0),
    }
    neutral = {"root": (0.0, 0.0, 0.0)}
    keys = [
        (0.0, neutral),
        (0.15, guard),
        (0.45, guard),
        (duration, neutral),
    ]
    return _build_keyframed("block", duration, keys, loop=False)


def knockdown(duration=2.4):
    down = {
        "spine_01": (-0.55, 0, 0), "spine_02": (-0.45, 0, 0),
        "neck_01": (-0.35, 0, 0),
        "upperarm_l": (-0.9, 0, 0.5), "upperarm_r": (-0.9, 0, -0.5),
        "thigh_l": (0.25, 0, 0.1), "thigh_r": (0.15, 0, -0.1),
        "calf_l": (-0.35, 0, 0), "calf_r": (-0.25, 0, 0),
        "root": (0.0, -0.82, -0.15),
    }
    rising = {
        "thigh_l": (0.7, 0, 0.05), "thigh_r": (0.7, 0, -0.05),
        "calf_l": (-0.9, 0, 0), "calf_r": (-0.9, 0, 0),
        "spine_02": (0.25, 0, 0),
        "root": (0.0, -0.35, 0.0),
    }
    neutral = {"root": (0.0, 0.0, 0.0)}
    keys = [
        (0.0, neutral),
        (0.55, down),
        (1.5, down),
        (2.0, rising),
        (duration, neutral),
    ]
    return _build_keyframed("knockdown", duration, keys, loop=False)


def all_procedural():
    return [idle_proc(), walk_proc(), run_proc(), crouch(), aim_pose(),
            block(), knockdown()]
