/**
 * Which region's world data to load, out of the several a deployment can carry.
 *
 * `loadWorldData` has always taken a `baseUrl` and read four files out of it, so the
 * loader itself needed no change to support a second region. What was missing was
 * anything that could *name* one: `region.json` describes the region it sits beside, so
 * a client that had only ever seen one file could not discover that a second existed,
 * let alone ask for it. That is what `public/world/regions.json` is - an index of the
 * regions this deployment actually has, generated by
 * `services/world-data/tools/build-region-index.py` from each region's own wire files.
 *
 * Selection is a `?region=<id>` query parameter, for the same reason `?city=<slug>` is
 * how the Manhattan building demo is reached (`src/scene/cityDemo.ts`): a query
 * parameter can add a mode without a menu, a save slot, or a code path every other
 * screen has to know about, and a URL naming a region is shareable and testable. With no
 * parameter the default region loads, which is the Ohio River Valley and is what every
 * existing entry point already gets.
 *
 * The one thing this module refuses to do is guess. An unknown id is an error naming the
 * ids that do exist, not a silent fall back to the default: a player who asked for New
 * York and got Ohio would be reading a real map with the wrong name on it, and nothing
 * about the result would look wrong.
 */

import { cacheBust, WorldDataError } from "./load.js";

/**
 * One deployed region, as `public/world/regions.json` describes it.
 *
 * Every count here is read back out of the region's own files rather than asserted here,
 * so the index cannot claim a settlement count the region does not have. They are for a
 * picker to show and for the boot error to name; nothing loads from them.
 */
export interface RegionIndexEntry {
  id: string;
  name: string;
  /** Relative to `public/world/`, with a trailing slash. `"./"` is the default region. */
  path: string;
  bbox: { south: number; west: number; north: number; east: number };
  stateCoverage?: string;
  settlements: number;
  roads: number;
  rail: number;
  bootZoom: number;
  bootTiles: number;
  retrieved?: string;
  wireVersion?: number;
}

/** The shape of `public/world/regions.json`. */
export interface RegionIndex {
  default: string;
  regions: RegionIndexEntry[];
}

/**
 * Whether a fetched index is usable, and what is wrong with it if not.
 *
 * Returns the reason rather than throwing, so the caller decides: a missing index is a
 * deployment that predates multi-region and must fall back to the default region, while a
 * malformed one is corruption and should be loud.
 */
export function validateRegionIndex(payload: unknown): { index: RegionIndex } | { error: string } {
  if (typeof payload !== "object" || payload === null) {
    return { error: "regions.json is not an object" };
  }
  const raw = payload as Record<string, unknown>;
  if (typeof raw.default !== "string" || raw.default.length === 0) {
    return { error: "regions.json has no `default` region id" };
  }
  if (!Array.isArray(raw.regions) || raw.regions.length === 0) {
    return { error: "regions.json has no `regions` array" };
  }
  const seen = new Set<string>();
  for (const [position, item] of raw.regions.entries()) {
    if (typeof item !== "object" || item === null) {
      return { error: `regions.json entry ${position} is not an object` };
    }
    const entry = item as Record<string, unknown>;
    if (typeof entry.id !== "string" || entry.id.length === 0) {
      return { error: `regions.json entry ${position} has no id` };
    }
    if (typeof entry.path !== "string" || !entry.path.endsWith("/")) {
      // A path without a trailing slash resolves against its last segment as a *file*, so
      // `/world/nyc-metro` + `region.json` would request `/world/region.json` - the default
      // region's file. That is the exact mix-up a second region exists to prevent.
      return { error: `regions.json entry ${entry.id} has a path that does not end in "/"` };
    }
    if (typeof entry.name !== "string" || entry.name.length === 0) {
      return { error: `regions.json entry ${entry.id} has no name` };
    }
    if (seen.has(entry.id)) {
      return { error: `regions.json lists ${entry.id} twice` };
    }
    seen.add(entry.id);
  }
  if (!seen.has(raw.default)) {
    return {
      error: `regions.json names ${raw.default} as the default region but does not list it`,
    };
  }
  return { index: raw as unknown as RegionIndex };
}

/**
 * The world base URL to load, given the index, a requested id, and the configured base.
 *
 * `configuredBase` is what the client would have loaded anyway - `VITE_WORLD_DATA_URL`,
 * defaulting to `/world`. It is the base the index's relative paths resolve against, and
 * it is returned unchanged when there is no index, so a deployment with one region and a
 * build with `VITE_WORLD_DATA_URL` pointing at a CDN keeps working untouched.
 */
export function resolveRegionBaseUrl(
  index: RegionIndex | null,
  requestedId: string | null,
  configuredBase: string,
): string {
  const base = configuredBase.endsWith("/") ? configuredBase : `${configuredBase}/`;
  const root = new URL(base, location.href).href;
  // No index, or no region asked for: the deployment's own default, which is what every
  // entry point loaded before this module existed.
  if (!index || !requestedId) return root;
  const entry = index.regions.find((candidate) => candidate.id === requestedId);
  if (!entry) {
    const known = index.regions.map((candidate) => candidate.id).join(", ");
    throw new WorldDataError(
      "missing",
      `This world data has no region called "${requestedId}".`,
      `?region=${requestedId} is not one of the deployed regions: ${known}. ` +
        `The index is ${root}regions.json.`,
      false,
    );
  }
  return new URL(entry.path, root).href;
}

/**
 * Read `?region=` out of a query string.
 *
 * A bare `?region` or `?region=` is not a request for a region named "", it is a request
 * for the default - which is what a hand-typed URL usually means and what treating it as
 * an unknown id would punish.
 */
export function requestedRegionId(search: string): string | null {
  const raw = new URLSearchParams(search).get("region");
  if (raw === null) return null;
  const trimmed = raw.trim();
  return trimmed.length === 0 ? null : trimmed;
}

/**
 * Fetch and validate `regions.json` from the world base directory.
 *
 * Returns `null` for a 404, because a deployment that predates multi-region has no index
 * and must still load its one region - the same reasoning `loadWorldData` uses for an
 * absent `boundaries.json`. Everything else is loud: a 500 or unparseable bytes means the
 * index is there and unreadable, and quietly loading the default region would mean the
 * player asked for New York and got Ohio with nothing on screen saying so.
 *
 * A *malformed* index is also loud, for the same reason. It is not absence; it is a file
 * that claims to list regions and cannot be believed, and the error names what is wrong so
 * it can be fixed rather than worked around.
 */
export async function loadRegionIndex(configuredBase: string): Promise<RegionIndex | null> {
  const base = configuredBase.endsWith("/") ? configuredBase : `${configuredBase}/`;
  const url = new URL("regions.json", new URL(base, location.href)).href;
  let response: Response;
  try {
    response = await fetch(cacheBust(url));
  } catch (err) {
    throw new WorldDataError(
      "network",
      `The world survey could not be reached. Check the connection and try again.`,
      `fetch(${url}) threw for the region index: ${String(err)}`,
    );
  }
  if (response.status === 404) return null;
  if (!response.ok) {
    throw new WorldDataError(
      "network",
      `The world survey returned an error loading the region list.`,
      `GET ${url} -> HTTP ${response.status} ${response.statusText}`,
    );
  }
  let parsed: unknown;
  try {
    parsed = await response.json();
  } catch (err) {
    throw new WorldDataError(
      "decode",
      `The world survey's region list is damaged. Fetch the world data again.`,
      `JSON.parse of ${url} threw: ${String(err)}`,
    );
  }
  const checked = validateRegionIndex(parsed);
  if ("error" in checked) {
    throw new WorldDataError(
      "decode",
      `The world survey's region list is damaged, so the map cannot be drawn.`,
      `GET ${url}: ${checked.error}`,
      false,
    );
  }
  return checked.index;
}