/**
 * The audio manifest has to describe the audio that ships.
 *
 * It did not. `public/audio/audio` held 6,318 files and the manifest listed 109
 * of them, so `AudioManager.preload` resolved almost every name the game asked
 * for to nothing and every music pool, bark and ambience bed outside that 109
 * was silent. These tests are the guard against that coming back: they walk the
 * real directory, so a file added without a manifest entry fails here rather
 * than playing silence in the browser.
 *
 * The manifest and the index are generated by
 * `services/world-data/tools/build-audio-manifest.py`.
 */

import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { webAudioPath } from "../AudioManager.js";

const CAMPAIGN_ROOT = fileURLToPath(new URL("../../..", import.meta.url));
const REPO_ROOT = fileURLToPath(new URL("../../../../..", import.meta.url));
const AUDIO_ROOT = join(CAMPAIGN_ROOT, "public", "audio");
const PUBLIC_DIR = join(CAMPAIGN_ROOT, "public");

const manifest = JSON.parse(readFileSync(join(PUBLIC_DIR, "audio-manifest.json"), "utf8")) as {
  runtimeIndex?: string;
  count?: number;
  assets: Array<{
    id: string;
    path: string;
    category?: string;
    loop?: boolean;
    bytes?: number;
    sha256?: string;
  }>;
};
const index = JSON.parse(readFileSync(join(AUDIO_ROOT, "audio-index.json"), "utf8")) as {
  count?: number;
  paths: Record<string, string>;
};

/** Every .mp3 under public/audio, as paths relative to the repo root. */
function shippedAudioFiles(dir = AUDIO_ROOT, found: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) shippedAudioFiles(full, found);
    else if (full.endsWith(".mp3") || full.endsWith(".wav")) found.push(relative(REPO_ROOT, full));
  }
  return found;
}

const files = shippedAudioFiles().map((path) => path.split(sep).join("/")).sort();
const byId = new Map(manifest.assets.map((asset) => [asset.id, asset]));
const byPath = new Map(manifest.assets.map((asset) => [asset.path, asset]));

describe("the manifest is honest about what ships", () => {
  it("has at least the library the pools draw on", () => {
    expect(manifest.assets.length).toBeGreaterThan(6_000);
    expect(manifest.assets.length).toBe(files.length);
    expect(manifest.count).toBe(files.length);
  });

  it("lists every shipped audio file, by its real path", () => {
    const unlisted = files.filter((path) => !byPath.has(path));
    expect(unlisted, `not in audio-manifest.json: ${unlisted.slice(0, 8).join(", ")}`).toEqual([]);
  });

  it("points at nothing that is not there", () => {
    const missing = manifest.assets
      .filter((asset) => !existsSync(join(REPO_ROOT, asset.path)))
      .map((asset) => asset.path);
    expect(missing, `listed but absent: ${missing.slice(0, 8).join(", ")}`).toEqual([]);
  });

  it("gives every entry a unique id", () => {
    const seen = new Set<string>();
    const duplicates: string[] = [];
    for (const asset of manifest.assets) {
      if (seen.has(asset.id)) duplicates.push(asset.id);
      seen.add(asset.id);
    }
    expect(duplicates).toEqual([]);
  });

  it("records the size on disk, not a stale one", () => {
    const wrong = manifest.assets
      .filter((asset) => statSync(join(REPO_ROOT, asset.path)).size !== asset.bytes)
      .map((asset) => asset.id);
    expect(wrong).toEqual([]);
  });

  it("stores a digest for every entry", () => {
    const undigested = manifest.assets.filter((asset) => !/^[0-9a-f]{64}$/.test(asset.sha256 ?? ""));
    expect(undigested.map((asset) => asset.id)).toEqual([]);
  });

  it("stores repository paths, which webAudioPath turns into fetchable ones", () => {
    for (const asset of manifest.assets) {
      expect(asset.path.startsWith("clients/campaign/public/")).toBe(true);
      expect(webAudioPath(asset.path).startsWith("/audio/")).toBe(true);
    }
  });
});

describe("the runtime index", () => {
  it("is what the ledger points the mixer at", () => {
    expect(manifest.runtimeIndex).toBe("audio/audio-index.json");
  });

  it("covers exactly the same ids as the ledger", () => {
    expect(index.count).toBe(manifest.assets.length);
    const indexIds = Object.keys(index.paths).sort();
    const manifestIds = manifest.assets.map((asset) => asset.id).sort();
    expect(indexIds).toEqual(manifestIds);
  });

  it("gives every id a web-root path that exists", () => {
    for (const [id, path] of Object.entries(index.paths)) {
      expect(path.startsWith("/audio/"), `${id} -> ${path}`).toBe(true);
      expect(existsSync(join(PUBLIC_DIR, path.slice(1))), `${id} -> ${path} is not served`).toBe(true);
    }
  });
});

describe("the ids the audio code speaks", () => {
  // Every one of these was a name the mixer asked for. Any of them missing turns
  // a real gameplay event into silence, so they are pinned here.
  const REQUIRED = [
    "menu-theme",
    "loading-theme",
    "battle-theme",
    "battle-theme-stem-drums",
    "battle-theme-stem-bass",
    "battle-theme-stem-fx",
    "battle-theme-stem-lead",
    "victory-fanfare",
    "defeat",
    "sfx-ambience-town-day",
    "sfx-ambience-town-night",
    "sfx-ambience-rain",
    "sfx-ambience-wind",
    "sfx-ambience-distant-battle",
    "sfx-foley-footstep-concrete",
    "sfx-foley-footstep-dirt",
    "sfx-foley-footstep-grass",
    "sfx-radio-blip",
    "sfx-radio-squelch",
    "sfx-radio-static",
    "sfx-ui-click",
    "sfx-ui-confirm",
    "sfx-ui-error",
    "sfx-ui-hover",
    "sfx-ui-toggle",
    "sfx-vehicle-engine-cruise",
    "sfx-vehicle-engine-idle",
    "sfx-vehicle-engine-load",
    "sfx-weapon-dry-fire",
    "sfx-weapon-explosion",
    "sfx-weapon-explosion-small",
    "sfx-weapon-pistol",
    "sfx-weapon-reload",
    "sfx-weapon-rifle",
    "sfx-weapon-shotgun",
    "sfx-weapon-smg-burst",
  ];

  it.each(REQUIRED)("resolves %s", (id) => {
    expect(byId.has(id), `${id} is not in audio-manifest.json`).toBe(true);
    expect(existsSync(join(REPO_ROOT, byId.get(id)!.path))).toBe(true);
  });
});

describe("families", () => {
  it("classifies every entry", () => {
    const counts = new Map<string, number>();
    for (const asset of manifest.assets) {
      counts.set(asset.category ?? "", (counts.get(asset.category ?? "") ?? 0) + 1);
    }
    // The five families the id scheme produces: full mixes, stems, barks, cries, sfx.
    expect(counts.get("music")).toBeGreaterThan(200);
    expect(counts.get("music-stem")).toBeGreaterThan(1_000);
    expect(counts.get("voice-bark")).toBeGreaterThan(3_000);
    expect(counts.get("voice-cry")).toBe(42);
    expect(counts.get("sfx-ambience")).toBeGreaterThan(20);
  });

  it("marks the beds as loops and the music as not", () => {
    const loops = manifest.assets.filter((asset) => asset.loop);
    expect(loops.every((asset) => asset.category !== "music")).toBe(true);
    expect(loops.some((asset) => asset.id === "sfx-ambience-town-day")).toBe(true);
    expect(loops.some((asset) => asset.id === "sfx-crowd-cheer-loop")).toBe(true);
  });
});