package campaign

// Companion catalog: hireable NPCs for tavern recruitment.
var companionPool = []Companion{
	{ID: "marcus_reed", Name: "Marcus Reed", Backstory: "Fifteen years on Columbus PD. Walked when the captain took envelopes.", Traits: []string{TraitHonorable, TraitCautious}, Skills: map[string]int{SkillScout: 70, SkillFighter: 55, SkillMedic: 30}, WageDaily: 12, RecruitKind: RecruitReputation, RecruitValue: 15, HometownHint: "Columbus"},
	{ID: "sofia_marchetti", Name: "Sofia Marchetti", Backstory: "Ran numbers until the feds flipped half the crew. Hamilton still pays her cut.", Traits: []string{TraitGreedy, TraitSarcastic}, Skills: map[string]int{SkillQuartermaster: 75, SkillScout: 40, SkillFighter: 35}, WageDaily: 18, RecruitKind: RecruitGold, RecruitValue: 600, HometownHint: "Hamilton"},
	{ID: "chen_wei", Name: "Chen Wei", Backstory: "ER trauma surgeon. Now stitches people in a panel van for cash.", Traits: []string{TraitLoyal, TraitCautious}, Skills: map[string]int{SkillMedic: 90, SkillQuartermaster: 35, SkillFighter: 20}, WageDaily: 22, RecruitKind: RecruitGold, RecruitValue: 700, HometownHint: "Athens"},
	{ID: "kim_jisoo", Name: "Kim Jisoo", Backstory: "Competition shooter. Two hundred yards is a conversation.", Traits: []string{TraitCautious, TraitRuthless}, Skills: map[string]int{SkillScout: 80, SkillFighter: 65, SkillMedic: 25}, WageDaily: 16, RecruitKind: RecruitWinFight, RecruitValue: 1, HometownHint: "Columbus"},
	{ID: "sean_obrien", Name: "Sean O'Brien", Backstory: "Bare-knuckle circuit. Never leaves a man behind.", Traits: []string{TraitHotHeaded, TraitLoyal}, Skills: map[string]int{SkillFighter: 80, SkillMedic: 20, SkillScout: 30}, WageDaily: 10, RecruitKind: RecruitGold, RecruitValue: 450, HometownHint: "Marion"},
	{ID: "maria_santos", Name: "Maria Santos", Backstory: "Built warehouses. Collected unpaid debts with a pipe wrench.", Traits: []string{TraitRuthless, TraitHonorable}, Skills: map[string]int{SkillEngineer: 70, SkillQuartermaster: 55, SkillFighter: 50}, WageDaily: 14, RecruitKind: RecruitReputation, RecruitValue: 10, HometownHint: "Dayton"},
	{ID: "derek_hollis", Name: "Derek Hollis", Backstory: "Army combat medic, two tours. VA lost his paperwork.", Traits: []string{TraitLoyal, TraitJoker}, Skills: map[string]int{SkillMedic: 85, SkillFighter: 45, SkillScout: 40}, WageDaily: 15, RecruitKind: RecruitGold, RecruitValue: 500, HometownHint: "Toledo"},
	{ID: "anya_volkov", Name: "Anya Volkov", Backstory: "Former PMC logistics. Convoy through any checkpoint.", Traits: []string{TraitSarcastic, TraitCautious}, Skills: map[string]int{SkillQuartermaster: 80, SkillScout: 55, SkillEngineer: 40}, WageDaily: 17, RecruitKind: RecruitGold, RecruitValue: 650, HometownHint: "Cleveland"},
	{ID: "jamal_wright", Name: "Jamal Wright", Backstory: "Learned welding in juvie. Built illicit armor.", Traits: []string{TraitRuthless, TraitLoyal}, Skills: map[string]int{SkillEngineer: 75, SkillFighter: 50, SkillQuartermaster: 30}, WageDaily: 13, RecruitKind: RecruitWinFight, RecruitValue: 2, HometownHint: "Youngstown"},
	{ID: "elaine_burke", Name: "Elaine Burke", Backstory: "Prosecutor who refused to bury a case. Forced out.", Traits: []string{TraitHonorable, TraitSarcastic}, Skills: map[string]int{SkillScout: 60, SkillQuartermaster: 50, SkillMedic: 25}, WageDaily: 14, RecruitKind: RecruitReputation, RecruitValue: 25, HometownHint: "Cincinnati"},
	{ID: "hector_ruiz", Name: "Hector Ruiz", Backstory: "Demolitions. Bridges are suggestions.", Traits: []string{TraitHotHeaded, TraitGreedy}, Skills: map[string]int{SkillEngineer: 85, SkillFighter: 40, SkillScout: 35}, WageDaily: 19, RecruitKind: RecruitGold, RecruitValue: 800, HometownHint: "Toledo"},
	{ID: "gwen_morrissey", Name: "Gwen Morrissey", Backstory: "Paramedic. Cash only. No sirens.", Traits: []string{TraitLoyal, TraitSarcastic}, Skills: map[string]int{SkillMedic: 88, SkillScout: 35, SkillFighter: 25}, WageDaily: 18, RecruitKind: RecruitGold, RecruitValue: 550, HometownHint: "Cleveland"},
	{ID: "vito_caruso", Name: "Vito Caruso", Backstory: "Chop-shop mechanic. Cops know his face.", Traits: []string{TraitGreedy, TraitJoker}, Skills: map[string]int{SkillEngineer: 78, SkillQuartermaster: 40, SkillScout: 45}, WageDaily: 13, RecruitKind: RecruitGold, RecruitValue: 480, HometownHint: "Cincinnati"},
	{ID: "frank_delgado", Name: "Frank Delgado", Backstory: "Border patrol washout. Knows every back road.", Traits: []string{TraitRuthless, TraitCautious}, Skills: map[string]int{SkillScout: 82, SkillFighter: 55, SkillQuartermaster: 25}, WageDaily: 14, RecruitKind: RecruitWinFight, RecruitValue: 3, HometownHint: "Toledo"},
	{ID: "nadia_hassan", Name: "Nadia Hassan", Backstory: "Civil engineer. Bridge failed after skimmed rebar.", Traits: []string{TraitHonorable, TraitSarcastic}, Skills: map[string]int{SkillEngineer: 88, SkillQuartermaster: 45, SkillScout: 30}, WageDaily: 20, RecruitKind: RecruitReputation, RecruitValue: 18, HometownHint: "Columbus"},
	{ID: "ray_cooper", Name: "Ray Cooper", Backstory: "Ex-con. Loyal if fed; gone if not.", Traits: []string{TraitHotHeaded, TraitGreedy}, Skills: map[string]int{SkillFighter: 70, SkillScout: 50, SkillEngineer: 30}, WageDaily: 10, RecruitKind: RecruitGold, RecruitValue: 350, HometownHint: "Mansfield"},
	{ID: "priya_nair", Name: "Priya Nair", Backstory: "Pharmacist. Stretches a med kit past the label.", Traits: []string{TraitCautious, TraitLoyal}, Skills: map[string]int{SkillMedic: 80, SkillQuartermaster: 45, SkillScout: 30}, WageDaily: 16, RecruitKind: RecruitGold, RecruitValue: 550, HometownHint: "Akron"},
	{ID: "darnell_hayes", Name: "Darnell Hayes", Backstory: "Football coach. Kids still listen.", Traits: []string{TraitLoyal, TraitHonorable}, Skills: map[string]int{SkillFighter: 60, SkillMedic: 35, SkillQuartermaster: 50}, WageDaily: 9, RecruitKind: RecruitReputation, RecruitValue: 8, HometownHint: "Canton"},
	{ID: "troy_nolan", Name: "Troy Nolan", Backstory: "Long-haul trucker. Runs guns when freight dries up.", Traits: []string{TraitJoker, TraitCautious}, Skills: map[string]int{SkillScout: 65, SkillQuartermaster: 60, SkillEngineer: 35}, WageDaily: 11, RecruitKind: RecruitGold, RecruitValue: 400, HometownHint: "Lima"},
	{ID: "renee_caldwell", Name: "Renee Caldwell", Backstory: "Corrections officer. Counts heads, spots runners.", Traits: []string{TraitRuthless, TraitCautious}, Skills: map[string]int{SkillScout: 70, SkillFighter: 55, SkillQuartermaster: 40}, WageDaily: 12, RecruitKind: RecruitReputation, RecruitValue: 12, HometownHint: "Mansfield"},
	{ID: "asha_bennett", Name: "Asha Bennett", Backstory: "Reporter who published one story too many.", Traits: []string{TraitHonorable, TraitCautious}, Skills: map[string]int{SkillScout: 72, SkillQuartermaster: 35, SkillMedic: 20}, WageDaily: 12, RecruitKind: RecruitReputation, RecruitValue: 20, HometownHint: "Dayton"},
	{ID: "owen_fitz", Name: "Owen Fitzpatrick", Backstory: "Union steward. Keeps a crew fed and angry.", Traits: []string{TraitHonorable, TraitHotHeaded}, Skills: map[string]int{SkillQuartermaster: 70, SkillFighter: 45, SkillMedic: 25}, WageDaily: 11, RecruitKind: RecruitWinFight, RecruitValue: 1, HometownHint: "Youngstown"},
	{ID: "suki_tanaka", Name: "Suki Tanaka", Backstory: "IT contractor. Burned the ransomware keys.", Traits: []string{TraitSarcastic, TraitGreedy}, Skills: map[string]int{SkillScout: 75, SkillEngineer: 60, SkillQuartermaster: 30}, WageDaily: 20, RecruitKind: RecruitGold, RecruitValue: 900, HometownHint: "Columbus"},
	{ID: "lillian_park", Name: "Lillian Park", Backstory: "Funeral director. Keeps the living functional.", Traits: []string{TraitCautious, TraitLoyal}, Skills: map[string]int{SkillMedic: 70, SkillQuartermaster: 55, SkillScout: 25}, WageDaily: 13, RecruitKind: RecruitGold, RecruitValue: 420, HometownHint: "Akron"},
}
