package config

// This file maps the Config struct onto balance file keys. It is deliberately
// mechanical: one line per constant, key spelled out in full. A generated
// mapping would hide typos, and a typo in a key name here would silently leave
// a constant at zero, which is the exact failure CONSTITUTION.md section 1.2
// forbids. The loader's unused-key check catches a key written here that the
// file lacks, and the missing-key check catches the reverse.

func (l *loader) load(c *Config) {
	c.Version = l.str("meta.version")

	// --- world ---
	c.World.Years = l.f64("world.years")
	c.World.MinTowns = l.f64("world.min_towns")
	c.World.MaxTowns = l.f64("world.max_towns")
	c.World.TownsPerState = l.f64("world.towns_per_state")
	c.World.VillagesPerTown = l.f64("world.villages_per_town")
	c.World.RulersPerTown = l.f64("world.rulers_per_town")
	c.World.MinRulers = l.f64("world.min_rulers")
	c.World.MaxRulers = l.f64("world.max_rulers")
	c.World.FoodDaysTarget = l.f64("world.food_days_target")
	c.World.StartMoneyPerCapita = l.f64("world.start_money_per_capita")
	c.World.StartMetalPerCapita = l.f64("world.start_metal_per_capita")
	c.World.TownGoldPerCapita = l.f64("world.town_gold_per_capita")
	c.World.StartGoldPerRuler = l.f64("world.start_gold_per_ruler")
	c.World.StartSanitation = l.f64("world.start_sanitation")
	c.World.MedicinePerCapita = l.f64("world.medicine_per_capita")
	c.World.GarrisonPerCapita = l.f64("world.garrison_per_capita")
	c.World.RouteDensity = l.f64("world.route_density")
	c.World.PortFraction = l.f64("world.port_fraction")
	c.World.TerrainSpeed = l.f64("world.terrain_speed")
	c.World.InitialWarChance = l.f64("world.initial_war_chance")
	c.World.AllyChance = l.f64("world.ally_chance")
	c.World.PartyTroopsBase = l.f64("world.party_troops_base")
	c.World.PartyTroopsPerInfluence = l.f64("world.party_troops_per_influence")
	c.World.RulerTraitSpread = l.f64("world.ruler_trait_spread")
	c.World.MercenaryFraction = l.f64("world.mercenary_fraction")
	c.World.WarlordFraction = l.f64("world.warlord_fraction")
	c.World.BirthRate = l.f64("world.birth_rate")
	c.World.FullFoodDays = l.f64("world.full_food_days")
	c.World.StarvingBirthFloor = l.f64("world.starving_birth_floor")
	c.World.SmallTownPopulation = l.f64("world.small_town_population")
	c.World.LargeTownPopulation = l.f64("world.large_town_population")
	c.World.SizeExponent = l.f64("world.size_exponent")
	c.World.StartUnrestMax = l.f64("world.start_unrest_max")
	c.World.PortProsperityBonus = l.f64("world.port_prosperity_bonus")
	c.World.VillagePopShareMin = l.f64("world.village_pop_share_min")
	c.World.VillagePopShareMax = l.f64("world.village_pop_share_max")
	c.World.VillageSpread = l.f64("world.village_spread")
	c.World.VillageYieldShare = l.f64("world.village_yield_share")
	c.World.VillageFoodDays = l.f64("world.village_food_days")
	c.World.RoadLengthOverDistance = l.f64("world.road_length_over_distance")
	c.World.RouteExtraRoughness = l.f64("world.route_extra_roughness")
	c.World.CoastalPortBoost = l.f64("world.coastal_port_boost")
	c.World.FarmlandNeighbourLeagues = l.f64("world.farmland_neighbour_leagues")
	c.World.FarmlandDensityScale = l.f64("world.farmland_density_scale")
	c.World.FarmlandCrowdingPenalty = l.f64("world.farmland_crowding_penalty")
	c.World.StartPartyFoodDays = l.f64("world.start_party_food_days")
	c.World.PartyMetalPerTroop = l.f64("world.party_metal_per_troop")
	c.World.PartyMedicinePerTroop = l.f64("world.party_medicine_per_troop")
	c.World.MinPartyTroops = l.f64("world.min_party_troops")
	c.World.MinRaiderBands = l.f64("world.min_raider_bands")
	c.World.MaxRaiderBands = l.f64("world.max_raider_bands")
	c.World.GovernorShare = l.f64("world.governor_share")
	c.World.LordShare = l.f64("world.lord_share")
	c.World.SideTreasuryBase = l.f64("world.side_treasury_base")
	c.World.SideGoldBase = l.f64("world.side_gold_base")
	c.World.SideMetalBase = l.f64("world.side_metal_base")
	c.World.SideFoodBase = l.f64("world.side_food_base")
	c.World.MapWidthLeagues = l.f64("world.map_width_leagues")
	c.World.MapHeightLeagues = l.f64("world.map_height_leagues")

	// --- food ---
	c.Food.PersonDaysPerPersonDay = l.f64("food.person_days_per_person_day")
	c.Food.WorkerFoodShare = l.f64("food.worker_food_share")
	c.Food.BaseYieldPerWorker = l.f64("food.base_yield_per_worker")
	c.Food.FarmlandFactor = l.f64("food.farmland_factor")
	c.Food.FarmlandMin = l.f64("food.farmland_min")
	c.Food.FarmlandMax = l.f64("food.farmland_max")
	c.Food.SpoilageRate = l.f64("food.spoilage_rate")
	c.Food.SpoilageModSanitation = l.f64("food.spoilage_mod_sanitation")
	c.Food.ShockFraction = l.f64("food.shock_fraction")
	c.Food.ShockChance = l.f64("food.shock_chance")
	c.Food.StockFloor = l.f64("food.stock_floor")
	c.Food.TradeInRate = l.f64("food.trade_in_rate")
	c.Food.TradeOutRate = l.f64("food.trade_out_rate")
	c.Food.ImportShortfall = l.f64("food.import_shortfall")
	c.Food.MaxDailyNetChange = l.f64("food.max_daily_net_change")

	// --- starvation ---
	c.Starve.DeathRate = l.f64("starvation.death_rate")
	c.Starve.GraceDays = l.f64("starvation.grace_days")
	c.Starve.UnrestPerDay = l.f64("starvation.unrest_per_day")
	c.Starve.WorkerLossRate = l.f64("starvation.worker_loss_rate")
	c.Starve.SanitationLossPerDay = l.f64("starvation.sanitation_loss_per_day")
	c.Starve.LoyaltyLossPerDay = l.f64("starvation.loyalty_loss_per_day")
	c.Starve.SeverityAtDeath = l.f64("starvation.severity_at_death")
	c.Starve.MoraleHit = l.f64("starvation.morale_hit")
	c.Starve.CrowdingDeathWeight = l.f64("starvation.crowding_death_weight")
	c.Starve.SanitationDeathWeight = l.f64("starvation.sanitation_death_weight")
	c.Starve.TinyTownPopulation = l.f64("starvation.tiny_town_population")
	c.Starve.RecoveryFoodDays = l.f64("starvation.recovery_food_days")

	// --- disease ---
	c.Disease.BaseContactRate = l.f64("disease.base_contact_rate")
	c.Disease.CrowdingWeight = l.f64("disease.crowding_weight")
	c.Disease.SanitationWeight = l.f64("disease.sanitation_weight")
	c.Disease.RecoveryRate = l.f64("disease.recovery_rate")
	c.Disease.CaseFatality = l.f64("disease.case_fatality")
	c.Disease.MedicineEfficacy = l.f64("disease.medicine_efficacy")
	c.Disease.DosesPerInfected = l.f64("disease.doses_per_infected")
	c.Disease.WorkerLossPerInfected = l.f64("disease.worker_loss_per_infected")
	c.Disease.UnrestPerDeath = l.f64("disease.unrest_per_death")
	c.Disease.LoyaltyLossPerDeath = l.f64("disease.loyalty_loss_per_death")
	c.Disease.CrowdingDecay = l.f64("disease.crowding_decay")
	c.Disease.UnrestPerInfected = l.f64("disease.unrest_per_infected")
	c.Disease.SanitationLossPerCrowding = l.f64("disease.sanitation_loss_per_crowding")
	c.Disease.ImmunityFloor = l.f64("disease.immunity_floor")
	c.Disease.MedicineDecayRate = l.f64("disease.medicine_decay_rate")

	// --- labor ---
	c.Labor.HealthyWorkerShare = l.f64("labor.healthy_worker_share")
	c.Labor.MaxWorkerShare = l.f64("labor.max_worker_share")
	c.Labor.MinWorkerShare = l.f64("labor.min_worker_share")
	c.Labor.WorkerRecoveryRate = l.f64("labor.worker_recovery_rate")
	c.Labor.ProsperityFromWorkers = l.f64("labor.prosperity_from_workers")
	c.Labor.ProsperityFromSanitation = l.f64("labor.prosperity_from_sanitation")
	c.Labor.ProsperityDecay = l.f64("labor.prosperity_decay")
	c.Labor.ProsperityCap = l.f64("labor.prosperity_cap")
	c.Labor.UnrestFromUnemployment = l.f64("labor.unrest_from_unemployment")
	c.Labor.UnemploymentThreshold = l.f64("labor.unemployment_threshold")
	c.Labor.UnemploymentMax = l.f64("labor.unemployment_max")

	// --- market ---
	c.Market.BasePrice = l.f64("market.base_price")
	c.Market.PriceElasticity = l.f64("market.price_elasticity")
	c.Market.PriceFloor = l.f64("market.price_floor")
	c.Market.PriceCap = l.f64("market.price_cap")
	c.Market.PriceInertia = l.f64("market.price_inertia")
	c.Market.RoadSafetyWeight = l.f64("market.road_safety_weight")
	c.Market.WagesShare = l.f64("market.wages_share")
	c.Market.WageFollowRate = l.f64("market.wage_follow_rate")
	c.Market.ScarcityForPrice = l.f64("market.scarcity_for_price")
	c.Market.PriceUnrestWeight = l.f64("market.price_unrest_weight")
	c.Market.StockTargetDays = l.f64("market.stock_target_days")
	c.Market.StockTargetTaxDrag = l.f64("market.stock_target_tax_drag")
	c.Market.MedicineScarcityWeight = l.f64("market.medicine_scarcity_weight")
	c.Market.MetalScarcityWeight = l.f64("market.metal_scarcity_weight")

	// --- currency ---
	c.Currency.WagesPerTroop = l.f64("currency.wages_per_troop")
	c.Currency.GarrisonWageShare = l.f64("currency.garrison_wage_share")
	c.Currency.TaxIncomePerCapita = l.f64("currency.tax_income_per_capita")
	c.Currency.TaxProsperityWeight = l.f64("currency.tax_prosperity_weight")
	c.Currency.TaxUnrestPenalty = l.f64("currency.tax_unrest_penalty")
	c.Currency.TaxLoyaltyPenalty = l.f64("currency.tax_loyalty_penalty")
	c.Currency.TaxMaxRate = l.f64("currency.tax_max_rate")
	c.Currency.TaxDefaultRate = l.f64("currency.tax_default_rate")
	c.Currency.TaxHarshUnrest = l.f64("currency.tax_harsh_unrest")
	c.Currency.BuildingUpkeepPerCapita = l.f64("currency.building_upkeep_per_capita")
	c.Currency.MarketFeeRate = l.f64("currency.market_fee_rate")
	c.Currency.TradeIncomePerCaravan = l.f64("currency.trade_income_per_caravan")
	c.Currency.GoldPerMoney = l.f64("currency.gold_per_money")
	c.Currency.ConversionCost = l.f64("currency.conversion_cost")
	c.Currency.InflationPerDeficit = l.f64("currency.inflation_per_deficit")
	c.Currency.InflationCap = l.f64("currency.inflation_cap")
	c.Currency.InflationUnrestWeight = l.f64("currency.inflation_unrest_weight")
	c.Currency.BankruptcyDebtFloor = l.f64("currency.bankruptcy_debt_floor")
	c.Currency.BorrowingPerDeficit = l.f64("currency.borrowing_per_deficit")
	c.Currency.InterestRate = l.f64("currency.interest_rate")
	c.Currency.ReserveSpendRate = l.f64("currency.reserve_spend_rate")
	c.Currency.MetalUsePerTroop = l.f64("currency.metal_use_per_troop")
	c.Currency.MetalMakeRate = l.f64("currency.metal_make_rate")
	c.Currency.SideDeficitShare = l.f64("currency.side_deficit_share")
	c.Currency.MercenaryGold = l.f64("currency.mercenary_gold")
	c.Currency.MercenaryWage = l.f64("currency.mercenary_wage")
	c.Currency.MercenaryValue = l.f64("currency.mercenary_value")
	c.Currency.MercenaryTroopScale = l.f64("currency.mercenary_troop_scale")

	// --- unrest ---
	c.Unrest.Decay = l.f64("unrest.decay")
	c.Unrest.FoodShortageWeight = l.f64("unrest.food_shortage_weight")
	c.Unrest.FoodDaysCritical = l.f64("unrest.food_days_critical")
	c.Unrest.TaxWeight = l.f64("unrest.tax_weight")
	c.Unrest.TaxComfortRate = l.f64("unrest.tax_comfort_rate")
	c.Unrest.GarrisonConductWeight = l.f64("unrest.garrison_conduct_weight")
	c.Unrest.ConductHarsh = l.f64("unrest.conduct_harsh")
	c.Unrest.DeathWeight = l.f64("unrest.death_weight")
	c.Unrest.DeathMemoryDays = l.f64("unrest.death_memory_days")
	c.Unrest.PropagandistWeight = l.f64("unrest.propagandist_weight")
	c.Unrest.PropagandistInfluence = l.f64("unrest.propagandist_influence")
	c.Unrest.UnrestCap = l.f64("unrest.unrest_cap")
	c.Unrest.LoyaltyFloorUnrest = l.f64("unrest.loyalty_floor_unrest")

	// --- loyalty ---
	c.Loyalty.RecoverRate = l.f64("loyalty.recover_rate")
	c.Loyalty.UnrestWeight = l.f64("loyalty.unrest_weight")
	c.Loyalty.TaxWeight = l.f64("loyalty.tax_weight")
	c.Loyalty.BrokenPromiseHit = l.f64("loyalty.broken_promise_hit")
	c.Loyalty.RaidHit = l.f64("loyalty.raid_hit")
	c.Loyalty.OutsideOfferWeight = l.f64("loyalty.outside_offer_weight")
	c.Loyalty.OutsideOfferBase = l.f64("loyalty.outside_offer_base")
	c.Loyalty.ServiceGain = l.f64("loyalty.service_gain")
	c.Loyalty.DefectionThreshold = l.f64("loyalty.defection_threshold")
	c.Loyalty.DefectionLoyaltyRequired = l.f64("loyalty.defection_loyalty_required")
	c.Loyalty.LoyaltyCap = l.f64("loyalty.loyalty_cap")
	c.Loyalty.OfferRangeLeagues = l.f64("loyalty.offer_range_leagues")
	c.Loyalty.StartLoyaltyMin = l.f64("loyalty.start_loyalty_min")
	c.Loyalty.StartLoyaltyMax = l.f64("loyalty.start_loyalty_max")
	c.Loyalty.OfferGap = l.f64("loyalty.offer_gap")
	c.Loyalty.OfferProximityWeight = l.f64("loyalty.offer_proximity_weight")

	// --- council ---
	c.Council.VoteThreshold = l.f64("council.vote_threshold")
	c.Council.UnrestRequired = l.f64("council.unrest_required")
	c.Council.DaysBelowThreshold = l.f64("council.days_below_threshold")
	c.Council.QuorumShare = l.f64("council.quorum_share")
	c.Council.CouncilorUnrestWeight = l.f64("council.councilor_unrest_weight")
	c.Council.CouncilorLoyaltyWeight = l.f64("council.councilor_loyalty_weight")
	c.Council.VoteChanceBase = l.f64("council.vote_chance_base")
	c.Council.VoteChanceUnrestWeight = l.f64("council.vote_chance_unrest_weight")
	c.Council.SuccessorPoolSize = l.f64("council.successor_pool_size")
	c.Council.InstabilityUnrestWeight = l.f64("council.instability_unrest_weight")
	c.Council.InstabilityThreshold = l.f64("council.instability_threshold")
	c.Council.InstabilityDailyChance = l.f64("council.instability_daily_chance")
	c.Council.LoyaltyDriftPerDay = l.f64("council.loyalty_drift_per_day")
	c.Council.LoyaltyStartMin = l.f64("council.loyalty_start_min")
	c.Council.LoyaltyStartMax = l.f64("council.loyalty_start_max")
	c.Council.QuorumRequired = l.f64("council.quorum_required")
	c.Council.InflectionLossOnHumiliation = l.f64("council.inflection_loss_on_humiliation")
	c.Council.InfluenceGainOnPromotion = l.f64("council.influence_gain_on_promotion")
	c.Council.LoyaltyAfterSuccession = l.f64("council.loyalty_after_succession")
	c.Council.SuccessorRangeLeagues = l.f64("council.successor_range_leagues")
	c.Council.SuccessorDistanceWeight = l.f64("council.successor_distance_weight")
	c.Council.SuccessorRelationWeight = l.f64("council.successor_relation_weight")
	c.Council.MercenaryPenalty = l.f64("council.mercenary_penalty")
	c.Council.SecessionLoyaltyCutoff = l.f64("council.secession_loyalty_cutoff")
	c.Council.SecessionRangeLeagues = l.f64("council.secession_range_leagues")

	// --- migration ---
	c.Migrate.FleeThreshold = l.f64("migration.flee_threshold")
	c.Migrate.FleeStarvationDays = l.f64("migration.flee_starvation_days")
	c.Migrate.FleeInfected = l.f64("migration.flee_infected")
	c.Migrate.MaxFleeShare = l.f64("migration.max_flee_share")
	c.Migrate.FleeToCapacityShare = l.f64("migration.flee_to_capacity_share")
	c.Migrate.CrowdingPerArrival = l.f64("migration.crowding_per_arrival")
	c.Migrate.CrowdingCap = l.f64("migration.crowding_cap")
	c.Migrate.CrowdingBase = l.f64("migration.crowding_base")
	c.Migrate.InfectionCarried = l.f64("migration.infection_carried")
	c.Migrate.AttractionShare = l.f64("migration.attraction_share")
	c.Migrate.ImmigrantsPerDayCap = l.f64("migration.immigrants_per_day_cap")
	c.Migrate.WorkerGainPerImmigrant = l.f64("migration.worker_gain_per_immigrant")
	c.Migrate.MaxMoveLeagues = l.f64("migration.max_move_leagues")
	c.Migrate.DesperationWeight = l.f64("migration.desperation_weight")
	c.Migrate.InfectionRepulsion = l.f64("migration.infection_repulsion")

	// --- security ---
	c.Security.PatrolCoverage = l.f64("security.patrol_coverage")
	c.Security.ConductEffect = l.f64("security.conduct_effect")
	c.Security.BaseRoadSafety = l.f64("security.base_road_safety")
	c.Security.RaiderSpawnRate = l.f64("security.raider_spawn_rate")
	c.Security.RaiderDecayRate = l.f64("security.raider_decay_rate")
	c.Security.RobChanceBase = l.f64("security.rob_chance_base")
	c.Security.RobChanceSafetyWeight = l.f64("security.rob_chance_safety_weight")
	c.Security.GarrisonDetachShare = l.f64("security.garrison_detach_share")
	c.Security.DeserterShare = l.f64("security.deserter_share")
	c.Security.MoraleGarrisonEffect = l.f64("security.morale_garrison_effect")
	c.Security.MinGarrisonForIsolated = l.f64("security.min_garrison_for_isolated")
	c.Security.StartGarrisonConduct = l.f64("security.start_garrison_conduct")
	c.Security.GoodConduct = l.f64("security.good_conduct")
	c.Security.RaiderGrowthFromSize = l.f64("security.raider_growth_from_size")
	c.Security.RaiderBandMin = l.f64("security.raider_band_min")
	c.Security.RaiderTroopPerStrength = l.f64("security.raider_troop_per_strength")
	c.Security.RaiderSafetyDrag = l.f64("security.raider_safety_drag")
	c.Security.TerrainSafetyDrag = l.f64("security.terrain_safety_drag")

	// --- logistics ---
	c.Logistic.SpeedPerDay = l.f64("logistics.speed_per_day")
	c.Logistic.SafetySpeedWeight = l.f64("logistics.safety_speed_weight")
	c.Logistic.TerrainSpeedWeight = l.f64("logistics.terrain_speed_weight")
	c.Logistic.SpoilagePerDay = l.f64("logistics.spoilage_per_day")
	c.Logistic.CaravanCapacity = l.f64("logistics.caravan_capacity")
	c.Logistic.CaravanFoodNeed = l.f64("logistics.caravan_food_need")
	c.Logistic.CaravanRiskDeath = l.f64("logistics.caravan_risk_death")
	c.Logistic.FoodShare = l.f64("logistics.food_share")
	c.Logistic.MedicineShare = l.f64("logistics.medicine_share")
	c.Logistic.MetalShare = l.f64("logistics.metal_share")
	c.Logistic.TradeMargin = l.f64("logistics.trade_margin")
	c.Logistic.BlockadeEffect = l.f64("logistics.blockade_effect")
	c.Logistic.CaravanLossUnrest = l.f64("logistics.caravan_loss_unrest")
	c.Logistic.CaravanGuards = l.f64("logistics.caravan_guards")
	c.Logistic.CaravanFoodDays = l.f64("logistics.caravan_food_days")
	c.Logistic.DispatchShare = l.f64("logistics.dispatch_share")
	c.Logistic.MinSurplusForCaravan = l.f64("logistics.min_surplus_for_caravan")
	c.Logistic.MinSafetyToDispatch = l.f64("logistics.min_safety_to_dispatch")
	c.Logistic.MaxCaravansPerRoute = l.f64("logistics.max_caravans_per_route")

	// --- upkeep ---
	c.Upkeep.MoraleWagesWeight = l.f64("upkeep.morale_wages_weight")
	c.Upkeep.MoraleFoodWeight = l.f64("upkeep.morale_food_weight")
	c.Upkeep.MoralePerOwedDay = l.f64("upkeep.morale_per_owed_day")
	c.Upkeep.WagesGraceDays = l.f64("upkeep.wages_grace_days")
	c.Upkeep.DesertionRate = l.f64("upkeep.desertion_rate")
	c.Upkeep.DesertionMoraleThreshold = l.f64("upkeep.desertion_morale_threshold")
	c.Upkeep.DesertionMaxShare = l.f64("upkeep.desertion_max_share")
	c.Upkeep.MoraleRecoveryRate = l.f64("upkeep.morale_recovery_rate")
	c.Upkeep.MoraleCap = l.f64("upkeep.morale_cap")
	c.Upkeep.WagesOwedPerDayUnpaid = l.f64("upkeep.wages_owed_per_day_unpaid")
	c.Upkeep.ContractChance = l.f64("upkeep.contract_chance")
	c.Upkeep.MilitiaCost = l.f64("upkeep.militia_cost")
	c.Upkeep.MilitiaMax = l.f64("upkeep.militia_max")
	c.Upkeep.MilitiaPerUnrest = l.f64("upkeep.militia_per_unrest")
	c.Upkeep.DesertionInfluenceLoss = l.f64("upkeep.desertion_influence_loss")
	c.Upkeep.LeadershipMoraleWeight = l.f64("upkeep.leadership_morale_weight")
	c.Upkeep.MinTroopsToPersist = l.f64("upkeep.min_troops_to_persist")

	// --- influence ---
	c.Influence.ServicePerDay = l.f64("influence.service_per_day")
	c.Influence.ServiceUnrestWeight = l.f64("influence.service_unrest_weight")
	c.Influence.VictoryInfluence = l.f64("influence.victory_influence")
	c.Influence.SiegeInfluence = l.f64("influence.siege_influence")
	c.Influence.BrokenOathInfluence = l.f64("influence.broken_oath_influence")
	c.Influence.DefectionInfluenceLoss = l.f64("influence.defection_influence_loss")
	c.Influence.InfluenceDecay = l.f64("influence.influence_decay")
	c.Influence.InfluenceCap = l.f64("influence.influence_cap")
	c.Influence.RenownPerVictory = l.f64("influence.renown_per_victory")
	c.Influence.RenownPerRaid = l.f64("influence.renown_per_raid")
	c.Influence.RenownPerBrokenOath = l.f64("influence.renown_per_broken_oath")
	c.Influence.RenownDecay = l.f64("influence.renown_decay")
	c.Influence.RenownCap = l.f64("influence.renown_cap")
	c.Influence.InfluenceDefectThreshold = l.f64("influence.influence_defect_threshold")
	c.Influence.RelationSpreadShare = l.f64("influence.relation_spread_share")
	c.Influence.LeaderInfluence = l.f64("influence.leader_influence")
	c.Influence.LeaderRenown = l.f64("influence.leader_renown")
	c.Influence.LeadershipUpkeep = l.f64("influence.leadership_upkeep")
	c.Influence.LoyaltyWearinessWeight = l.f64("influence.loyalty_weariness_weight")
	c.Influence.LoyaltyTreasuryWeight = l.f64("influence.loyalty_treasury_weight")
	c.Influence.LoyaltyVictoryWeight = l.f64("influence.loyalty_victory_weight")
	c.Influence.LoyaltyOwnTownWeight = l.f64("influence.loyalty_own_town_weight")
	c.Influence.LoyaltyOwnTownBonus = l.f64("influence.loyalty_own_town_bonus")

	// --- march ---
	c.March.SpeedPerDay = l.f64("march.speed_per_day")
	c.March.SafetySpeedWeight = l.f64("march.safety_speed_weight")
	c.March.TerrainSpeedWeight = l.f64("march.terrain_speed_weight")
	c.March.FatiguePerDay = l.f64("march.fatigue_per_day")
	c.March.FatigueDecay = l.f64("march.fatigue_decay")
	c.March.FatigueSpeedWeight = l.f64("march.fatigue_speed_weight")
	c.March.SizeSpeedWeight = l.f64("march.size_speed_weight")
	c.March.SizeReference = l.f64("march.size_reference")
	c.March.FoodPerTroop = l.f64("march.food_per_troop")
	c.March.MoneyPerTroop = l.f64("march.money_per_troop")
	c.March.MetalPerTroop = l.f64("march.metal_per_troop")
	c.March.LoadSpeedWeight = l.f64("march.load_speed_weight")
	c.March.MoraleMarchWeight = l.f64("march.morale_march_weight")
	c.March.ArrivalMoraleBonus = l.f64("march.arrival_morale_bonus")
	c.March.TerrainFatigueWeight = l.f64("march.terrain_fatigue_weight")
	c.March.StationaryFoodRate = l.f64("march.stationary_food_rate")
	c.March.MinSpeed = l.f64("march.min_speed")
	c.March.WinterSeverity = l.f64("march.winter_severity")
	c.March.SeasonSeverity = l.f64("march.season_severity")
	c.March.WeatherSwing = l.f64("march.weather_swing")
	c.March.ExposureWeight = l.f64("march.exposure_weight")

	// --- supply ---
	c.Supply.ResupplyFraction = l.f64("supply.resupply_fraction")
	c.Supply.ResupplyDistanceWeight = l.f64("supply.resupply_distance_weight")
	c.Supply.DaysOfFoodStarved = l.f64("supply.days_of_food_starved")
	c.Supply.StarvingMoraleLoss = l.f64("supply.starving_morale_loss")
	c.Supply.HomeStockReserve = l.f64("supply.home_stock_reserve")
	c.Supply.BlockedResupply = l.f64("supply.blocked_resupply")
	c.Supply.SupplyMoraleBonus = l.f64("supply.supply_morale_bonus")
	c.Supply.AttritionSpeedWeight = l.f64("supply.attrition_speed_weight")
	c.Supply.ResupplyRangeLeagues = l.f64("supply.resupply_range_leagues")
	c.Supply.BlockadeBlockSupply = l.f64("supply.blockade_block_supply")

	// --- attrition ---
	c.Attrition.ExhaustionRate = l.f64("attrition.exhaustion_rate")
	c.Attrition.DiseaseRate = l.f64("attrition.disease_rate")
	c.Attrition.DiseaseFromCrowding = l.f64("attrition.disease_from_crowding")
	c.Attrition.DiseaseFromSanitation = l.f64("attrition.disease_from_sanitation")
	c.Attrition.MedicineEfficacy = l.f64("attrition.medicine_efficacy")
	c.Attrition.FatigueThreshold = l.f64("attrition.fatigue_threshold")
	c.Attrition.CasualtyMoraleHit = l.f64("attrition.casualty_morale_hit")
	c.Attrition.CasualtyCap = l.f64("attrition.casualty_cap")
	c.Attrition.TerrainAttritionWeight = l.f64("attrition.terrain_attrition_weight")
	c.Attrition.WoundedRecoveryRate = l.f64("attrition.wounded_recovery_rate")
	c.Attrition.WoundedRecoveryMedicineWeight = l.f64("attrition.wounded_recovery_medical_weight")
	c.Attrition.DiseaseRecoveryRate = l.f64("attrition.disease_recovery_rate")
	c.Attrition.CrowdingReferenceTroops = l.f64("attrition.crowding_reference_troops")
	c.Attrition.MedicinePerTroop = l.f64("attrition.medicine_per_troop")
	c.Attrition.MedicinePerDeath = l.f64("attrition.medicine_per_death")
	c.Attrition.DeadShare = l.f64("attrition.dead_share")
	c.Attrition.StarvationExhaustionWeight = l.f64("attrition.starvation_exhaustion_weight")
	c.Attrition.SupplyRangeReference = l.f64("attrition.supply_range_reference")
	c.Attrition.MinTroopsToPersist = l.f64("attrition.min_troops_to_persist")

	// --- siege ---
	c.Siege.FoodBurnPerTroop = l.f64("siege.food_burn_per_troop")
	c.Siege.AttritionPerDay = l.f64("siege.attrition_per_day")
	c.Siege.DiseasePerDay = l.f64("siege.disease_per_day")
	c.Siege.SanitationLossPerDay = l.f64("siege.sanitation_loss_per_day")
	c.Siege.LoyaltyLossPerDay = l.f64("siege.loyalty_loss_per_day")
	c.Siege.UnrestLossPerDay = l.f64("siege.unrest_loss_per_day")
	c.Siege.GateOpenFoodDays = l.f64("siege.gate_open_food_days")
	c.Siege.GateOpenLoyalty = l.f64("siege.gate_open_loyalty")
	c.Siege.GateOpenUnrest = l.f64("siege.gate_open_unrest")
	c.Siege.GateOpenChance = l.f64("siege.gate_open_chance")
	c.Siege.MaxDays = l.f64("siege.max_days")
	c.Siege.EquipmentPerBreachDay = l.f64("siege.equipment_per_breach_day")
	c.Siege.BreachDays = l.f64("siege.breach_days")
	c.Siege.ReliefRadius = l.f64("siege.relief_radius")
	c.Siege.MinTroopsToBesiege = l.f64("siege.min_troops_to_besiege")
	c.Siege.CrowdingPerDay = l.f64("siege.crowding_per_day")
	c.Siege.BreachWorkPerDay = l.f64("siege.breach_work_per_day")
	c.Siege.GatePatienceDays = l.f64("siege.gate_patience_days")
	c.Siege.InfluenceLossOnFall = l.f64("siege.influence_loss_on_fall")
	c.Siege.InfluenceLossOnFailedSiege = l.f64("siege.influence_loss_on_failed_siege")
	c.Siege.LoyaltyAfterSurrender = l.f64("siege.loyalty_after_surrender")
	c.Siege.RenownForBloodlessWin = l.f64("siege.renown_for_bloodless_win")

	// --- relation ---
	c.Relation.GiftRelation = l.f64("relation.gift_relation")
	c.Relation.GiftGoldToRelation = l.f64("relation.gift_gold_to_relation")
	c.Relation.BattleRelation = l.f64("relation.battle_relation")
	c.Relation.RaidRelation = l.f64("relation.raid_relation")
	c.Relation.BrokenOathRelation = l.f64("relation.broken_oath_relation")
	c.Relation.BrokenOathSpread = l.f64("relation.broken_oath_spread")
	c.Relation.SharedEnemyRelation = l.f64("relation.shared_enemy_relation")
	c.Relation.DefectionRelation = l.f64("relation.defection_relation")
	c.Relation.RelationCap = l.f64("relation.relation_cap")
	c.Relation.RelationFloor = l.f64("relation.relation_floor")
	c.Relation.DriftPerDay = l.f64("relation.drift_per_day")
	c.Relation.CoalitionThreshold = l.f64("relation.coalition_threshold")
	c.Relation.CoalitionSpreadTolerance = l.f64("relation.coalition_spread_tolerance")
	c.Relation.TrustDecayPerBetrayal = l.f64("relation.trust_decay_per_betrayal")
	c.Relation.StartRelationMean = l.f64("relation.start_relation_mean")
	c.Relation.StartRelationSpread = l.f64("relation.start_relation_spread")
	c.Relation.StartAllyRelationMin = l.f64("relation.start_ally_relation_min")
	c.Relation.StartAllyRelationMax = l.f64("relation.start_ally_relation_max")
	c.Relation.AlliedRelationBonus = l.f64("relation.allied_relation_bonus")
	c.Relation.AllyThreshold = l.f64("relation.ally_threshold")
	c.Relation.SideDriftShare = l.f64("relation.side_drift_share")
	c.Relation.SideInheritRate = l.f64("relation.side_inherit_rate")
	c.Relation.CoalitionQuorumShare = l.f64("relation.coalition_quorum_share")

	// --- ruler ai ---
	c.RulerAI.AttackWeight = l.f64("ruler_ai.attack_weight")
	c.RulerAI.TargetWeaknessWeight = l.f64("ruler_ai.target_weakness_weight")
	c.RulerAI.DefendWeight = l.f64("ruler_ai.defend_weight")
	c.RulerAI.RaidWeight = l.f64("ruler_ai.raid_weight")
	c.RulerAI.AidWeight = l.f64("ruler_ai.aid_weight")
	c.RulerAI.TradeWeight = l.f64("ruler_ai.trade_weight")
	c.RulerAI.RestWeight = l.f64("ruler_ai.rest_weight")
	c.RulerAI.DistancePenalty = l.f64("ruler_ai.distance_penalty")
	c.RulerAI.SupplyCheckFood = l.f64("ruler_ai.supply_check_food")
	c.RulerAI.OverextensionMorale = l.f64("ruler_ai.overextension_morale")
	c.RulerAI.TraitAttackWeight = l.f64("ruler_ai.trait_attack_weight")
	c.RulerAI.TraitAidWeight = l.f64("ruler_ai.trait_aid_weight")
	c.RulerAI.TraitTradeWeight = l.f64("ruler_ai.trait_trade_weight")
	c.RulerAI.TraitRestWeight = l.f64("ruler_ai.trait_rest_weight")
	c.RulerAI.TraitRaidWeight = l.f64("ruler_ai.trait_raid_weight")
	c.RulerAI.AmbitionLandWeight = l.f64("ruler_ai.ambition_land_weight")
	c.RulerAI.AmbitionWealthWeight = l.f64("ruler_ai.ambition_wealth_weight")
	c.RulerAI.AmbitionRevengeWeight = l.f64("ruler_ai.ambition_revenge_weight")
	c.RulerAI.AmbitionSecurityWeight = l.f64("ruler_ai.ambition_security_weight")
	c.RulerAI.HateWeight = l.f64("ruler_ai.hate_weight")
	c.RulerAI.Randomness = l.f64("ruler_ai.randomness")
	c.RulerAI.TaxRaiseUnrestTolerance = l.f64("ruler_ai.tax_raise_unrest_tolerance")
	c.RulerAI.TaxCutLoyaltyGain = l.f64("ruler_ai.tax_cut_loyalty_gain")
	c.RulerAI.ExecuteChance = l.f64("ruler_ai.execute_chance")
	c.RulerAI.PrisonerRansomGold = l.f64("ruler_ai.prisoner_ransom_gold")
	c.RulerAI.PrisonerRansomRelation = l.f64("ruler_ai.prisoner_ransom_relation")
	c.RulerAI.DecideEveryDays = l.f64("ruler_ai.decide_every_days")
	c.RulerAI.StarvingArmyPenalty = l.f64("ruler_ai.starving_army_penalty")
	c.RulerAI.LowSupplyPenalty = l.f64("ruler_ai.low_supply_penalty")
	c.RulerAI.AidBlockedByOwnCrisis = l.f64("ruler_ai.aid_blocked_by_own_crisis")
	c.RulerAI.StarvingTargetWeakness = l.f64("ruler_ai.starving_target_weakness")
	c.RulerAI.GrievanceHateThreshold = l.f64("ruler_ai.grievance_hate_threshold")
	c.RulerAI.AttackBlockedByHomeThreat = l.f64("ruler_ai.attack_blocked_by_home_threat")
	c.RulerAI.DefectWeight = l.f64("ruler_ai.defect_weight")
	c.RulerAI.DefectLeaderWeariness = l.f64("ruler_ai.defect_leader_weariness")
	c.RulerAI.DefectLeaderDebt = l.f64("ruler_ai.defect_leader_debt")
	c.RulerAI.DefectOwnCollapse = l.f64("ruler_ai.defect_own_collapse")
	c.RulerAI.PeaceWeight = l.f64("ruler_ai.peace_weight")
	c.RulerAI.BlockadeWeight = l.f64("ruler_ai.blockade_weight")
	c.RulerAI.AidRangeLeagues = l.f64("ruler_ai.aid_range_leagues")
	c.RulerAI.AidFoodThreshold = l.f64("ruler_ai.aid_food_threshold")
	c.RulerAI.AttackRangeLeagues = l.f64("ruler_ai.attack_range_leagues")
	c.RulerAI.TargetFoodDays = l.f64("ruler_ai.target_food_days")
	c.RulerAI.TargetUnrestWeight = l.f64("ruler_ai.target_unrest_weight")
	c.RulerAI.TargetMinPopulationScale = l.f64("ruler_ai.target_min_population_scale")
	c.RulerAI.IntelligenceBlurMax = l.f64("ruler_ai.intelligence_blur_max")
	c.RulerAI.IntelligenceScale = l.f64("ruler_ai.intelligence_scale")
	c.RulerAI.RaidRangeLeagues = l.f64("ruler_ai.raid_range_leagues")
	c.RulerAI.RaidFoodPerCapita = l.f64("ruler_ai.raid_food_per_capita")
	c.RulerAI.RaidMemoryDecayDays = l.f64("ruler_ai.raid_memory_decay_days")
	c.RulerAI.TradeRangeLeagues = l.f64("ruler_ai.trade_range_leagues")
	c.RulerAI.TradePriceSensitivity = l.f64("ruler_ai.trade_price_sensitivity")
	c.RulerAI.BlockadeImportDependency = l.f64("ruler_ai.blockade_import_dependency")
	c.RulerAI.BlockadeTargetFoodDays = l.f64("ruler_ai.blockade_target_food_days")
	c.RulerAI.TaxCapacityFromProsperity = l.f64("ruler_ai.tax_capacity_from_prosperity")
	c.RulerAI.TaxCapacityFromUnrest = l.f64("ruler_ai.tax_capacity_from_unrest")
	c.RulerAI.TaxGenerosityWeight = l.f64("ruler_ai.tax_generosity_weight")
	c.RulerAI.TaxCalculationWeight = l.f64("ruler_ai.tax_calculation_weight")
	c.RulerAI.TaxNeedReference = l.f64("ruler_ai.tax_need_reference")
	c.RulerAI.TaxNeedPressure = l.f64("ruler_ai.tax_need_pressure")
	c.RulerAI.TaxFearUnrestRate = l.f64("ruler_ai.tax_fear_unrest_rate")
	c.RulerAI.TaxCutLoyaltyThreshold = l.f64("ruler_ai.tax_cut_loyalty_threshold")
	c.RulerAI.TaxChangeRate = l.f64("ruler_ai.tax_change_rate")

	// --- faction ai ---
	c.FactionAI.DeclareWarWeight = l.f64("faction_ai.declare_war_weight")
	c.FactionAI.TargetWeaknessWeight = l.f64("faction_ai.target_weakness_weight")
	c.FactionAI.ResourceNeedWeight = l.f64("faction_ai.resource_need_weight")
	c.FactionAI.ExhaustionPeaceWeight = l.f64("faction_ai.exhaustion_peace_weight")
	c.FactionAI.TreasuryPeaceWeight = l.f64("faction_ai.treasury_peace_weight")
	c.FactionAI.OfferPeaceThreshold = l.f64("faction_ai.offer_peace_threshold")
	c.FactionAI.WarWearinessPerDay = l.f64("faction_ai.war_weariness_per_day")
	c.FactionAI.WarWearinessFromBattle = l.f64("faction_ai.war_weariness_from_battle")
	c.FactionAI.TributeShare = l.f64("faction_ai.tribute_share")
	c.FactionAI.VassalTributeRate = l.f64("faction_ai.vassal_tribute_rate")
	c.FactionAI.RaidThreshold = l.f64("faction_ai.raid_threshold")
	c.FactionAI.TradePactBonusPerDay = l.f64("faction_ai.trade_pact_bonus_per_day")
	c.FactionAI.AllyJoinThreshold = l.f64("faction_ai.ally_join_threshold")
	c.FactionAI.DecideEveryDays = l.f64("faction_ai.decide_every_days")
	c.FactionAI.OvermatchRatio = l.f64("faction_ai.overmatch_ratio")
	c.FactionAI.HostileRelationThreshold = l.f64("faction_ai.hostile_relation_threshold")
	c.FactionAI.RevengeRelationThreshold = l.f64("faction_ai.revenge_relation_threshold")
	c.FactionAI.FoodNeedWeight = l.f64("faction_ai.food_need_weight")
	c.FactionAI.MetalNeedWeight = l.f64("faction_ai.metal_need_weight")
	c.FactionAI.FoodNeedWarThreshold = l.f64("faction_ai.food_need_war_threshold")
	c.FactionAI.DeclareWarThreshold = l.f64("faction_ai.declare_war_threshold")
	c.FactionAI.PeaseDecisionThreshold = l.f64("faction_ai.pease_decision_threshold")
	c.FactionAI.PeaceWearinessRelief = l.f64("faction_ai.peace_weariness_relief")
	c.FactionAI.PeaceRelationGain = l.f64("faction_ai.peace_relation_gain")
	c.FactionAI.IntensityPerBattle = l.f64("faction_ai.intensity_per_battle")
	c.FactionAI.VassalStrengthRatio = l.f64("faction_ai.vassal_strength_ratio")
	c.FactionAI.VassalStrengthShare = l.f64("faction_ai.vassal_strength_share")
	c.FactionAI.VassalChancePerPeace = l.f64("faction_ai.vassal_chance_per_peace")
	c.FactionAI.InfluenceCostOfWar = l.f64("faction_ai.influence_cost_of_war")
	c.FactionAI.HostileRelationShare = l.f64("faction_ai.hostile_relation_share")
	c.FactionAI.ActRelationThreshold = l.f64("faction_ai.act_relation_threshold")
	c.FactionAI.PactRelationThreshold = l.f64("faction_ai.pact_relation_threshold")

	// --- cause ---
	c.Cause.MinAbsolute = l.f64("cause.min_absolute")
	c.Cause.MinRelative = l.f64("cause.min_relative")
	c.Cause.MaxChainLinks = l.f64("cause.max_chain_links")
	c.Cause.MinChainLinks = l.f64("cause.min_chain_links")

	// --- audit ---
	c.Audit.ChainMinFraction = l.f64("audit.chain_min_fraction")
	c.Audit.DominanceMaxFraction = l.f64("audit.dominance_max_fraction")
	c.Audit.SampleEventsPerRun = l.f64("audit.sample_events_per_run")
	c.Audit.SideSurvivalThreshold = l.f64("audit.side_survival_threshold")
	c.Audit.SideCollapseThreshold = l.f64("audit.side_collapse_threshold")
	c.Audit.LogRowLimit = l.f64("audit.log_row_limit")

	// --- ruler ---
	c.Ruler.AgeMin = l.f64("ruler.age_min")
	c.Ruler.AgeMax = l.f64("ruler.age_max")
	c.Ruler.BaseInfluence = l.f64("ruler.base_influence")
	c.Ruler.InfluencePerTier = l.f64("ruler.influence_per_tier")
	c.Ruler.RenownFromInfluence = l.f64("ruler.renown_from_influence")
	c.Ruler.StartMoney = l.f64("ruler.start_money")
	c.Ruler.PartyKeepChance = l.f64("ruler.party_keep_chance")
	c.Ruler.MaxPartyTroopsBase = l.f64("ruler.max_party_troops_base")
	c.Ruler.MaxPartyTroopsPerRenown = l.f64("ruler.max_party_troops_per_renown")
	c.Ruler.PartyMoneyShare = l.f64("ruler.party_money_share")
	c.Ruler.PartyGoldShare = l.f64("ruler.party_gold_share")
	c.Ruler.MercenaryCaravanChance = l.f64("ruler.mercenary_caravan_chance")

	// --- campaign ---
	c.Campaign.BreakMorale = l.f64("campaign.break_morale")
	c.Campaign.BreakAfterDaysOut = l.f64("campaign.break_after_days_out")
	c.Campaign.MinDaysFoodToMarch = l.f64("campaign.min_days_food_to_march")
	c.Campaign.MinMetalToBesiege = l.f64("campaign.min_metal_to_besiege")
	c.Campaign.RaidRangeLeagues = l.f64("campaign.raid_range_leagues")
	c.Campaign.RaidMemoryDecayDays = l.f64("campaign.raid_memory_decay_days")
	c.Campaign.AidRangeLeagues = l.f64("campaign.aid_range_leagues")
	c.Campaign.AidFoodThreshold = l.f64("campaign.aid_food_threshold")
	c.Campaign.AidLoadShare = l.f64("campaign.aid_load_share")
	c.Campaign.AidMedicineShare = l.f64("campaign.aid_medicine_share")
	c.Campaign.TradeRangeLeagues = l.f64("campaign.trade_range_leagues")
	c.Campaign.TradeCapitalShare = l.f64("campaign.trade_capital_share")
	c.Campaign.AttackRangeLeagues = l.f64("campaign.attack_range_leagues")
	c.Campaign.TargetFoodDays = l.f64("campaign.target_food_days")
	c.Campaign.GarrisonAdvantage = l.f64("campaign.garrison_advantage")
	c.Campaign.TargetMinPopulationScale = l.f64("campaign.target_min_population_scale")
	c.Campaign.TaxCutLoyaltyRate = l.f64("campaign.tax_cut_loyalty_rate")
	c.Campaign.CaretakerMedicineStock = l.f64("campaign.caretaker_medicine_stock")
	c.Campaign.TraderTaxCeiling = l.f64("campaign.trader_tax_ceiling")
	c.Campaign.TradeMinRoadSafety = l.f64("campaign.trade_min_road_safety")
	c.Campaign.AidOrderShare = l.f64("campaign.aid_order_share")
	c.Campaign.MedicineUnitPrice = l.f64("campaign.medicine_unit_price")
	c.Campaign.FortifyMetalPerLevel = l.f64("campaign.fortify_metal_per_level")
	c.Campaign.FortifyMoraleBonus = l.f64("campaign.fortify_morale_bonus")

	// --- election ---
	c.Election.TermYears = l.f64("election.term_years")
	c.Election.MaxTerms = l.f64("election.max_terms")
	c.Election.AssassinationBaseRate = l.f64("election.assassination_base_rate")
	c.Election.TravelRiskMultiplier = l.f64("election.travel_risk_multiplier")
	c.Election.UnrestRiskScale = l.f64("election.unrest_risk_scale")

	// --- construction ---
	c.Construction.MaxLevel = l.f64("construction.max_level")
	c.Construction.DaysPerCost = l.f64("construction.days_per_cost")
	c.Construction.CostWalls = [3]float64{
		l.f64("construction.cost_walls_t1"),
		l.f64("construction.cost_walls_t2"),
		l.f64("construction.cost_walls_t3"),
	}
	c.Construction.CostBarracks = [3]float64{
		l.f64("construction.cost_barracks_t1"),
		l.f64("construction.cost_barracks_t2"),
		l.f64("construction.cost_barracks_t3"),
	}
	c.Construction.CostTraining = [3]float64{
		l.f64("construction.cost_training_t1"),
		l.f64("construction.cost_training_t2"),
		l.f64("construction.cost_training_t3"),
	}
	c.Construction.CostCommunity = [3]float64{
		l.f64("construction.cost_community_t1"),
		l.f64("construction.cost_community_t2"),
		l.f64("construction.cost_community_t3"),
	}
	c.Construction.CostCommercial = [3]float64{
		l.f64("construction.cost_commercial_t1"),
		l.f64("construction.cost_commercial_t2"),
		l.f64("construction.cost_commercial_t3"),
	}
	c.Construction.CostWarehouse = [3]float64{
		l.f64("construction.cost_warehouse_t1"),
		l.f64("construction.cost_warehouse_t2"),
		l.f64("construction.cost_warehouse_t3"),
	}
	c.Construction.CostFarms = [3]float64{
		l.f64("construction.cost_farms_t1"),
		l.f64("construction.cost_farms_t2"),
		l.f64("construction.cost_farms_t3"),
	}
	c.Construction.CostWatch = [3]float64{
		l.f64("construction.cost_watch_t1"),
		l.f64("construction.cost_watch_t2"),
		l.f64("construction.cost_watch_t3"),
	}
	c.Construction.CostInfra = [3]float64{
		l.f64("construction.cost_infra_t1"),
		l.f64("construction.cost_infra_t2"),
		l.f64("construction.cost_infra_t3"),
	}
	c.Construction.CostCivic = [3]float64{
		l.f64("construction.cost_civic_t1"),
		l.f64("construction.cost_civic_t2"),
		l.f64("construction.cost_civic_t3"),
	}
	c.Construction.AutoBuildReserve = l.f64("construction.auto_build_reserve")
	c.Construction.CommunityLoyaltyPerLevel = l.f64("construction.community_loyalty_per_level")
	c.Construction.InfraProsperityPerLevel = l.f64("construction.infra_prosperity_per_level")
	c.Construction.FarmsFoodPerLevel = l.f64("construction.farms_food_per_level")
	c.Construction.WatchMilitiaPerLevel = l.f64("construction.watch_militia_per_level")
	c.Construction.CommercialTaxPerLevel = l.f64("construction.commercial_tax_per_level")
	c.Construction.CivicInfluencePerLevel = l.f64("construction.civic_influence_per_level")
	c.Construction.TrainingMoralePerLevel = l.f64("construction.training_morale_per_level")
	c.Construction.WarehouseFoodCapPerLevel = l.f64("construction.warehouse_food_cap_per_level")
	c.Construction.WarehouseBaseCap = l.f64("construction.warehouse_base_cap")
	c.Construction.BarracksGarrisonCapPerLevel = [3]float64{
		l.f64("construction.barracks_garrison_cap_t1"),
		l.f64("construction.barracks_garrison_cap_t2"),
		l.f64("construction.barracks_garrison_cap_t3"),
	}
	c.Construction.GarrisonBaseCap = l.f64("construction.garrison_base_cap")

	// --- taxation ---
	c.Taxation.StateTaxMaxRate = l.f64("taxation.state_tax_max_rate")
	c.Taxation.StateTaxDefault = l.f64("taxation.state_tax_default")

	// --- siege ---
	c.Siege.WallLevelSlowdown = l.f64("siege.wall_level_slowdown")
	// --- battle ---
	// Battle size is a knob. MaxUnitsPerSide is a validation limit the battle
	// engine errors on, never an allocation size: the engine sizes every array
	// and grid from the forces it is given.
	c.Battle.MaxUnitsPerSide = l.f64("battle.max_units_per_side")
	c.Battle.TickSeconds = l.f64("battle.tick_seconds")
	c.Battle.MaxTicks = l.f64("battle.max_ticks")
	c.Battle.GridCellSize = l.f64("battle.grid_cell_size")
	c.Battle.RangedGridCellSize = l.f64("battle.ranged_grid_cell_size")
	c.Battle.GridMaxCells = l.f64("battle.grid_max_cells")
	c.Battle.MaxReportEvents = l.f64("battle.max_report_events")
	c.Battle.ReferenceUnitsPerSide = l.f64("battle.reference_units_per_side")
	c.Battle.RosterHPBase = l.f64("battle.roster_hp_base")
	c.Battle.RosterHPSkillWeight = l.f64("battle.roster_hp_skill_weight")
	c.Battle.RosterSpeedBase = l.f64("battle.roster_speed_base")
	c.Battle.RosterSpeedSkillWeight = l.f64("battle.roster_speed_skill_weight")
	c.Battle.RosterRangedShare = l.f64("battle.roster_ranged_share")
	c.Battle.RosterMoraleBiasScale = l.f64("battle.roster_morale_bias_scale")
	c.Battle.RosterMeleeSkillMean = l.f64("battle.roster_melee_skill_mean")
	c.Battle.RosterMeleeSkillSpread = l.f64("battle.roster_melee_skill_spread")
	c.Battle.RosterRangedSkillMean = l.f64("battle.roster_ranged_skill_mean")
	c.Battle.RosterRangedSkillSpread = l.f64("battle.roster_ranged_skill_spread")
	c.Battle.RosterMoraleStart = l.f64("battle.roster_morale_start")
	c.Battle.RosterMoraleSpread = l.f64("battle.roster_morale_spread")
	c.Battle.RosterTroopsPerUnit = l.f64("battle.roster_troops_per_unit")
	c.Battle.RosterFrontage = l.f64("battle.roster_frontage")
	c.Battle.RosterStartDistance = l.f64("battle.roster_start_distance")
	c.Battle.RosterFormationDepth = l.f64("battle.roster_formation_depth")
	c.Battle.RosterFrontAspect = l.f64("battle.roster_front_aspect")
	c.Battle.RosterLeadersPerUnit = l.f64("battle.roster_leaders_per_unit")
	c.Battle.RosterLeaderSpread = l.f64("battle.roster_leader_spread")
	c.Battle.RosterLeaderDepthFraction = l.f64("battle.roster_leader_depth_fraction")
	c.Battle.RosterLeaderJitterFraction = l.f64("battle.roster_leader_jitter_fraction")
	c.Battle.RosterLeaderInfluenceFloor = l.f64("battle.roster_leader_influence_floor")
	c.Battle.RosterLeaderInfluenceSpread = l.f64("battle.roster_leader_influence_spread")
	c.Battle.MeleeRange = l.f64("battle.melee_range")
	c.Battle.MeleeSwingSeconds = l.f64("battle.melee_swing_seconds")
	c.Battle.MeleeRangedSkillScale = l.f64("battle.melee_ranged_skill_scale")
	c.Battle.MeleeDamageBase = l.f64("battle.melee_damage_base")
	c.Battle.MeleeDamageSkillWeight = l.f64("battle.melee_damage_skill_weight")
	c.Battle.MeleeDamageSpeedWeight = l.f64("battle.melee_damage_speed_weight")
	c.Battle.MeleeArmorReduction = l.f64("battle.melee_armor_reduction")
	c.Battle.MeleeArmorReductionCap = l.f64("battle.melee_armor_reduction_cap")
	c.Battle.MeleeDamageVariance = l.f64("battle.melee_damage_variance")
	c.Battle.MeleeFatiguePerDamage = l.f64("battle.melee_fatigue_per_damage")
	c.Battle.MeleeRoutedEffectiveness = l.f64("battle.melee_routed_effectiveness")
	c.Battle.MeleeBrokenEffectiveness = l.f64("battle.melee_broken_effectiveness")
	c.Battle.RangedRange = l.f64("battle.ranged_range")
	c.Battle.RangedMinRange = l.f64("battle.ranged_min_range")
	c.Battle.RangedFireInterval = l.f64("battle.ranged_fire_interval")
	c.Battle.RangedHitChanceBase = l.f64("battle.ranged_hit_chance_base")
	c.Battle.RangedHitChanceSkillWeight = l.f64("battle.ranged_hit_chance_skill_weight")
	c.Battle.RangedHitEffectivenessFloor = l.f64("battle.ranged_hit_effectiveness_floor")
	c.Battle.RangedDamageBase = l.f64("battle.ranged_damage_base")
	c.Battle.RangedDamageSkillWeight = l.f64("battle.ranged_damage_skill_weight")
	c.Battle.RangedDamageVariance = l.f64("battle.ranged_damage_variance")
	c.Battle.RangedSuppressionShare = l.f64("battle.ranged_suppression_share")
	c.Battle.RangedSuppressionPerHit = l.f64("battle.ranged_suppression_per_hit")
	c.Battle.RosterAmmoPerUnit = l.f64("battle.roster_ammo_per_unit")
	c.Battle.SuppressionCap = l.f64("battle.suppression_cap")
	c.Battle.SuppressionDecay = l.f64("battle.suppression_decay")
	c.Battle.SuppressionMeleePenalty = l.f64("battle.suppression_melee_penalty")
	c.Battle.SuppressionRangedPenalty = l.f64("battle.suppression_ranged_penalty")
	c.Battle.RoutedExposure = l.f64("battle.routed_exposure")
	c.Battle.MoraleCasualtyHit = l.f64("battle.morale_casualty_hit")
	c.Battle.MoraleNeighbourhood = l.f64("battle.morale_neighbourhood")
	c.Battle.MoraleCasualtyFalloff = l.f64("battle.morale_casualty_falloff")
	c.Battle.MoraleSuppressionHit = l.f64("battle.morale_suppression_hit")
	c.Battle.MoraleRatioNeutral = l.f64("battle.morale_ratio_neutral")
	c.Battle.MoraleRatioWeight = l.f64("battle.morale_ratio_weight")
	c.Battle.MoraleRecovery = l.f64("battle.morale_recovery")
	c.Battle.MoraleRecoverySuppressionBand = l.f64("battle.morale_recovery_suppression_band")
	c.Battle.MoraleUnarmedHit = l.f64("battle.morale_unarmed_hit")
	c.Battle.MoraleLeaderBonus = l.f64("battle.morale_leader_bonus")
	c.Battle.MoraleLeaderRadius = l.f64("battle.morale_leader_radius")
	c.Battle.MoraleLeaderInfluenceReference = l.f64("battle.morale_leader_influence_reference")
	c.Battle.MoraleBreakThreshold = l.f64("battle.morale_break_threshold")
	c.Battle.MoraleRoutThreshold = l.f64("battle.morale_rout_threshold")
	c.Battle.MoraleFloor = l.f64("battle.morale_floor")
	c.Battle.RallyChance = l.f64("battle.rally_chance")
	c.Battle.RallyMoraleGain = l.f64("battle.rally_morale_gain")
	c.Battle.RallyRoutedChance = l.f64("battle.rally_routed_chance")
	c.Battle.RallyLeaderMultiplier = l.f64("battle.rally_leader_multiplier")
	c.Battle.MoralePanicSpread = l.f64("battle.morale_panic_spread")
	c.Battle.SurrenderMoraleReport = l.f64("battle.surrender_morale_report")
	c.Battle.ApproachSpeedScale = l.f64("battle.approach_speed_scale")
	c.Battle.ChargeSpeedScale = l.f64("battle.charge_speed_scale")
	c.Battle.WithdrawSpeedScale = l.f64("battle.withdraw_speed_scale")
	c.Battle.RoutSpeedScale = l.f64("battle.rout_speed_scale")
	c.Battle.StandoffDistance = l.f64("battle.standoff_distance")
	c.Battle.RoutFleeRadius = l.f64("battle.rout_flee_radius")
	c.Battle.ChargeDistance = l.f64("battle.charge_distance")
	c.Battle.MaxStepPerTick = l.f64("battle.max_step_per_tick")
	c.Battle.LateralDrift = l.f64("battle.lateral_drift")
	c.Battle.MeleeMaxTargets = l.f64("battle.melee_max_targets")
	c.Battle.MaxAttackersPerTarget = l.f64("battle.max_attackers_per_target")
	c.Battle.RangedMaxTargets = l.f64("battle.ranged_max_targets")
	c.Battle.TargetCasualtyWeight = l.f64("battle.target_casualty_weight")
	c.Battle.FatalHPFraction = l.f64("battle.fatal_hp_fraction")
	c.Battle.DeadShare = l.f64("battle.dead_share")
	c.Battle.FinishingBlowScale = l.f64("battle.finishing_blow_scale")
	c.Battle.ExhaustionCap = l.f64("battle.exhaustion_cap")
	c.Battle.ExhaustionPerAttack = l.f64("battle.exhaustion_per_attack")
	c.Battle.ExhaustionPerMetre = l.f64("battle.exhaustion_per_metre")
	c.Battle.ExhaustionRecovery = l.f64("battle.exhaustion_recovery")
	c.Battle.ExhaustionDamagePenalty = l.f64("battle.exhaustion_damage_penalty")
	c.Battle.ExhaustionSpeedPenalty = l.f64("battle.exhaustion_speed_penalty")
	c.Battle.SurrenderStrengthFraction = l.f64("battle.surrender_strength_fraction")
	c.Battle.RoutStrengthFraction = l.f64("battle.rout_strength_fraction")
	c.Battle.SurrenderRange = l.f64("battle.surrender_range")
	c.Battle.SurrenderChance = l.f64("battle.surrender_chance")

	// --- formation ---
	// internal/formation reads these through formation.FromCentral rather than
	// parsing the [formation] section itself. The reason is not tidiness, it is
	// that this loader is the only one: finish() rejects a balance file
	// containing a key no caller claimed, so a section owned by a second private
	// parser either stops the campaign runner from starting at all or has to be
	// claimed here without ever being read, which is what this block used to do
	// and what made the balance file unloadable by anything.
	//
	// Reading a constant is not a system calling another system
	// (CONSTITUTION.md section 2.1). internal/config is the loader for the whole
	// simulation, not one of the systems in CAUSE_EFFECT.md section 3, and
	// internal/battle already reads its constants the same way. What internal/
	// formation owns is what the numbers mean and how a body of men is arranged
	// from them; how they arrived from a file is not its business.
	c.Formation.FrontSpacing = l.f64("formation.front_spacing")
	c.Formation.RankSpacing = l.f64("formation.rank_spacing")
	c.Formation.LineFrontWidth = l.f64("formation.line_front_width")
	c.Formation.ColumnFrontWidth = l.f64("formation.column_front_width")
	c.Formation.WedgeTipUnits = l.f64("formation.wedge_tip_units")
	c.Formation.WedgeRowGrowth = l.f64("formation.wedge_row_growth")
	c.Formation.LooseSpacing = l.f64("formation.loose_spacing")
	c.Formation.LooseJitterFraction = l.f64("formation.loose_jitter_fraction")
	c.Formation.LooseSeed = l.f64("formation.loose_seed")
	c.Formation.MinSeparation = l.f64("formation.min_separation")
	c.Formation.SeparationIterations = l.f64("formation.separation_iterations")
	c.Formation.SeparationPushFraction = l.f64("formation.separation_push_fraction")
	c.Formation.SeparationPushMax = l.f64("formation.separation_push_max")
	c.Formation.HoldSpeed = l.f64("formation.hold_speed")
	c.Formation.AdvanceSpeed = l.f64("formation.advance_speed")
	c.Formation.ChargeSpeed = l.f64("formation.charge_speed")
	c.Formation.FlankSpeed = l.f64("formation.flank_speed")
	c.Formation.RetreatSpeed = l.f64("formation.retreat_speed")
	c.Formation.TurnRate = l.f64("formation.turn_rate")
	c.Formation.FaceTurnRateScale = l.f64("formation.face_turn_rate_scale")
	c.Formation.FaceEnemyWeight = l.f64("formation.face_enemy_weight")
	c.Formation.AdvanceStandoff = l.f64("formation.advance_standoff")
	c.Formation.ChargeStandoff = l.f64("formation.charge_standoff")
	c.Formation.RetreatDistance = l.f64("formation.retreat_distance")
	c.Formation.FlankStandoff = l.f64("formation.flank_standoff")
	c.Formation.FlankSweepDeg = l.f64("formation.flank_sweep_deg")
	c.Formation.FlankSweepRateDeg = l.f64("formation.flank_sweep_rate_deg")
	// What each shape does in contact, as opposed to where it stands. Read by
	// internal/battle: a formation order becomes movement there, and the shape
	// a unit is standing in becomes a multiplier in the melee and aimed-fire
	// stages. The same one-loader rule as the rest of the section applies, and
	// these are the keys that were missing for it: before them a shape could be
	// drawn on the field and nothing could be said about what it was worth.
	c.Formation.WedgeChargeDamageBonus = l.f64("formation.wedge_charge_damage_bonus")
	c.Formation.WedgeFlankTakenScale = l.f64("formation.wedge_flank_taken_scale")
	c.Formation.WedgeFlankArcDeg = l.f64("formation.wedge_flank_arc_deg")
	c.Formation.SquareFastMoverSpeed = l.f64("formation.square_fast_mover_speed")
	c.Formation.SquareFastMoverTakenScale = l.f64("formation.square_fast_mover_taken_scale")
	c.Formation.SquareMoveSpeedScale = l.f64("formation.square_move_speed_scale")
	c.Formation.SkirmishSuppressionTakenScale = l.f64("formation.skirmish_suppression_taken_scale")
	c.Formation.SkirmishMeleeTakenScale = l.f64("formation.skirmish_melee_taken_scale")

	// --- command ---
	// The tactics layer, internal/command. Same arrangement as [formation] and
	// for the same reason: one loader reads the whole balance file, so a section
	// read by a second private parser would either stop the campaign runner or
	// have to be claimed here without ever being read. The three shapes are
	// strings because they name a choice; internal/command resolves them
	// through formation.ParseFormation and refuses a name no shape implements.
	c.Command.FormationsPerSide = l.f64("command.formations_per_side")
	c.Command.ReserveShare = l.f64("command.reserve_share")
	c.Command.FrontShape = l.str("command.front_shape")
	c.Command.FlankShape = l.str("command.flank_shape")
	c.Command.ReserveShape = l.str("command.reserve_shape")
	c.Command.AdvanceTriggerRange = l.f64("command.advance_trigger_range")
	c.Command.ChargeRange = l.f64("command.charge_range")
	c.Command.ChargeStrengthRatio = l.f64("command.charge_strength_ratio")
	c.Command.FlankTriggerRange = l.f64("command.flank_trigger_range")
	c.Command.FlankMinStrengthFraction = l.f64("command.flank_min_strength_fraction")
	c.Command.ReserveCommitStrengthFraction = l.f64("command.reserve_commit_strength_fraction")
	c.Command.WithdrawMorale = l.f64("command.withdraw_morale")
	c.Command.WithdrawBrokenShare = l.f64("command.withdraw_broken_share")
	c.Command.DecisionIntervalTicks = l.f64("command.decision_interval_ticks")
	c.Command.OrderMinTicks = l.f64("command.order_min_ticks")
}
